# 📊 Project FORESIGHT

# AI-Powered Demand & Inventory Intelligence

## Notebook 01: Data Engineering & Validation

---

## 📌 Project Information

| Item | Details |
|------|---------|
| Author | L Pragna |
| Project | Project FORESIGHT |
| Internship | Zidio Development |
| Notebook | 01 |
| Version | 1.0 |
| Status | In Progress |
| Last Updated | August 2026 |

---

## 🎯 Purpose

This notebook builds the complete data engineering pipeline for Project FORESIGHT.

The notebook transforms the raw M5 Forecasting datasets into clean, validated, and business-ready datasets that will be used for:

- Exploratory Data Analysis (EDA)
- Feature Engineering
- Demand Forecasting
- Inventory Intelligence
- Power BI Dashboard
- Streamlit Application

---

> **Goal:** Produce reliable datasets for downstream analytics and machine learning.

# 🎯 Business Problem

Retail businesses frequently face inventory challenges because customer demand changes over time.

Demand is influenced by:

- Seasonal trends
- Holidays
- Promotions
- Product pricing
- Consumer buying behaviour

Poor demand estimation creates two major business problems:

- Overstocking, increasing storage costs and tying up working capital.
- Stockouts, leading to lost sales and dissatisfied customers.

Project FORESIGHT aims to solve these problems using a complete data analytics and machine learning pipeline that converts raw retail data into actionable business insights.

# 🎯 Notebook Objectives

The objective of Notebook 01 is to create a robust data engineering pipeline.

This notebook will:

- Load the raw M5 datasets.
- Understand the structure of each dataset.
- Assess data quality.
- Clean and validate the data.
- Integrate multiple datasets.
- Create business-ready datasets.
- Export processed datasets for later notebooks.

These datasets will serve as the foundation for the entire Project FORESIGHT workflow.

# 🔄 Project Workflow
```mermaid
flowchart TD

A[Raw M5 Datasets]

A --> B[Notebook 01<br>Data Engineering]

B --> C[Notebook 02<br>EDA]

C --> D[Notebook 03<br>Feature Engineering]

D --> E[Notebook 04<br>Baseline Forecast]

E --> F[Notebook 05<br>Machine Learning]

F --> G[Notebook 06<br>Model Evaluation]

G --> H[Notebook 07<br>Inventory Intelligence]

H --> I[Power BI Dashboard]

I --> J[Streamlit Application]
```

In [74]:
# ============================================================
# Notebook Configuration
# Project: FORESIGHT
# Notebook: 01 - Data Engineering & Validation
# ============================================================

import warnings

# Suppress non-critical warnings
warnings.filterwarnings("ignore")

print("✅ Notebook environment configured successfully.")

✅ Notebook environment configured successfully.

In [75]:
# ============================================================
# Import Required Libraries
# ============================================================

# Standard Library
from pathlib import Path

# Data Manipulation
import pandas as pd
import numpy as np

# Notebook Display
from IPython.display import display

# ============================================================
# Display Configuration
# ============================================================

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 150)
pd.set_option("display.float_format", "{:.2f}".format)

print("✅ Required libraries imported successfully.")

✅ Required libraries imported successfully.

In [76]:
# ============================================================
# Project Directory & File Paths
# ============================================================

# Project root (Notebook is inside /notebooks)
PROJECT_ROOT = Path.cwd().parent

# Data folders
RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"
INTERIM_DATA_DIR = PROJECT_ROOT / "data" / "interim"
PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"

# Source files
SALES_FILE = RAW_DATA_DIR / "sales_train_validation.csv"
CALENDAR_FILE = RAW_DATA_DIR / "calendar.csv"
PRICES_FILE = RAW_DATA_DIR / "sell_prices.csv"

print("📁 Project Root :", PROJECT_ROOT)
print("📂 Raw Data     :", RAW_DATA_DIR)
print("📂 Processed    :", PROCESSED_DATA_DIR)

print("\n✅ File paths configured successfully.")

📁 Project Root : c:\Users\Dell\OneDrive\Project_Foresight
📂 Raw Data     : c:\Users\Dell\OneDrive\Project_Foresight\data\raw
📂 Processed    : c:\Users\Dell\OneDrive\Project_Foresight\data\processed

✅ File paths configured successfully.

In [77]:
# ============================================================
# Load Raw M5 Datasets
# ============================================================

sales_df = pd.read_csv(SALES_FILE)
calendar_df = pd.read_csv(CALENDAR_FILE)
prices_df = pd.read_csv(PRICES_FILE)

print("✅ All datasets loaded successfully.\n")

print(f"Sales Dataset Shape      : {sales_df.shape}")
print(f"Calendar Dataset Shape   : {calendar_df.shape}")
print(f"Prices Dataset Shape     : {prices_df.shape}")

✅ All datasets loaded successfully.

Sales Dataset Shape      : (30490, 1919)
Calendar Dataset Shape   : (1969, 14)
Prices Dataset Shape     : (6841121, 4)

# 🔍 Source Data Understanding

Before cleaning or transforming the datasets, it is important to understand their structure, dimensions, and business purpose.

The three M5 datasets include:

- **Sales Dataset** – Historical daily sales for each SKU across stores.
- **Calendar Dataset** – Dates, events, holidays, and SNAP indicators.
- **Selling Prices Dataset** – Weekly selling prices for each SKU and store.

This understanding helps ensure accurate data integration and feature engineering in later stages.

In [78]:
# ============================================================
# Sales Dataset Preview
# ============================================================

display(sales_df.head())

print("\nRows :", sales_df.shape[0])
print("Columns :", sales_df.shape[1])

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,d_5,d_6,d_7,d_8,d_9,d_10,d_11,d_12,d_13,d_14,d_15,d_16,d_17,d_18,d_19,d_20,d_21,d_22,d_23,d_24,d_25,d_26,d_27,d_28,d_29,d_30,d_31,d_32,d_33,d_34,d_35,d_36,d_37,d_38,d_39,d_40,d_41,d_42,d_43,d_44,d_45,d_46,d_47,d_48,d_49,d_50,d_51,d_52,d_53,d_54,d_55,d_56,d_57,d_58,d_59,d_60,d_61,d_62,d_63,d_64,d_65,d_66,d_67,d_68,d_69,d_70,d_71,d_72,d_73,d_74,d_75,d_76,d_77,d_78,d_79,d_80,d_81,d_82,d_83,d_84,d_85,d_86,d_87,d_88,d_89,d_90,d_91,d_92,d_93,d_94,d_95,d_96,d_97,d_98,d_99,d_100,d_101,d_102,d_103,d_104,d_105,d_106,d_107,d_108,d_109,d_110,d_111,d_112,d_113,d_114,d_115,d_116,d_117,d_118,d_119,d_120,d_121,d_122,d_123,d_124,d_125,d_126,d_127,d_128,d_129,d_130,d_131,d_132,d_133,d_134,d_135,d_136,d_137,d_138,d_139,d_140,d_141,d_142,d_143,d_144,d_145,d_146,d_147,d_148,d_149,d_150,d_151,d_152,d_153,d_154,d_155,d_156,d_157,d_158,d_159,d_160,d_161,d_162,d_163,d_164,d_165,d_166,d_167,d_168,d_169,d_170,d_171,d_172,d_173,d_174,d_175,d_176,d_177,d_178,d_179,d_180,d_181,d_182,d_183,d_184,d_185,d_186,d_187,d_188,d_189,d_190,d_191,d_192,d_193,d_194,d_195,d_196,d_197,d_198,d_199,d_200,d_201,d_202,d_203,d_204,d_205,d_206,d_207,d_208,d_209,d_210,d_211,d_212,d_213,d_214,d_215,d_216,d_217,d_218,d_219,d_220,d_221,d_222,d_223,d_224,d_225,d_226,d_227,d_228,d_229,d_230,d_231,d_232,d_233,d_234,d_235,d_236,d_237,d_238,d_239,d_240,d_241,d_242,d_243,d_244,d_245,d_246,d_247,d_248,d_249,d_250,d_251,d_252,d_253,d_254,d_255,d_256,d_257,d_258,d_259,d_260,d_261,d_262,d_263,d_264,d_265,d_266,d_267,d_268,d_269,d_270,d_271,d_272,d_273,d_274,d_275,d_276,d_277,d_278,d_279,d_280,d_281,d_282,d_283,d_284,d_285,d_286,d_287,d_288,d_289,d_290,d_291,d_292,d_293,d_294,d_295,d_296,d_297,d_298,d_299,d_300,d_301,d_302,d_303,d_304,d_305,d_306,d_307,d_308,d_309,d_310,d_311,d_312,d_313,d_314,d_315,d_316,d_317,d_318,d_319,d_320,d_321,d_322,d_323,d_324,d_325,d_326,d_327,d_328,d_329,d_330,d_331,d_332,d_333,d_334,d_335,d_336,d_337,d_338,d_339,d_340,d_341,d_342,d_343,d_344,d_345,d_346,d_347,d_348,d_349,d_350,d_351,d_352,d_353,d_354,d_355,d_356,d_357,d_358,d_359,d_360,d_361,d_362,d_363,d_364,d_365,d_366,d_367,d_368,d_369,d_370,d_371,d_372,d_373,d_374,d_375,d_376,d_377,d_378,d_379,d_380,d_381,d_382,d_383,d_384,d_385,d_386,d_387,d_388,d_389,d_390,d_391,d_392,d_393,d_394,d_395,d_396,d_397,d_398,d_399,d_400,d_401,d_402,d_403,d_404,d_405,d_406,d_407,d_408,d_409,d_410,d_411,d_412,d_413,d_414,d_415,d_416,d_417,d_418,d_419,d_420,d_421,d_422,d_423,d_424,d_425,d_426,d_427,d_428,d_429,d_430,d_431,d_432,d_433,d_434,d_435,d_436,d_437,d_438,d_439,d_440,d_441,d_442,d_443,d_444,d_445,d_446,d_447,d_448,d_449,d_450,d_451,d_452,d_453,d_454,d_455,d_456,d_457,d_458,d_459,d_460,d_461,d_462,d_463,d_464,d_465,d_466,d_467,d_468,d_469,d_470,d_471,d_472,d_473,d_474,d_475,d_476,d_477,d_478,d_479,d_480,d_481,d_482,d_483,d_484,d_485,d_486,d_487,d_488,d_489,d_490,d_491,d_492,d_493,d_494,d_495,d_496,d_497,d_498,d_499,d_500,d_501,d_502,d_503,d_504,d_505,d_506,d_507,d_508,d_509,d_510,d_511,d_512,d_513,d_514,d_515,d_516,d_517,d_518,d_519,d_520,d_521,d_522,d_523,d_524,d_525,d_526,d_527,d_528,d_529,d_530,d_531,d_532,d_533,d_534,d_535,d_536,d_537,d_538,d_539,d_540,d_541,d_542,d_543,d_544,d_545,d_546,d_547,d_548,d_549,d_550,d_551,d_552,d_553,d_554,d_555,d_556,d_557,d_558,d_559,d_560,d_561,d_562,d_563,d_564,d_565,d_566,d_567,d_568,d_569,d_570,d_571,d_572,d_573,d_574,d_575,d_576,d_577,d_578,d_579,d_580,d_581,d_582,d_583,d_584,d_585,d_586,d_587,d_588,d_589,d_590,d_591,d_592,d_593,d_594,d_595,d_596,d_597,d_598,d_599,d_600,d_601,d_602,d_603,d_604,d_605,d_606,d_607,d_608,d_609,d_610,d_611,d_612,d_613,d_614,d_615,d_616,d_617,d_618,d_619,d_620,d_621,d_622,d_623,d_624,d_625,d_626,d_627,d_628,d_629,d_630,d_631,d_632,d_633,d_634,d_635,d_636,d_637,d_638,d_639,d_640,d_641,d_642,d_643,d_644,d_645,d_646,d_647,d_648,d_649,d_650,d_651,d_652,d_653,d_654,d_655,d_656,d_657,d_658,d_659,d_660,d_661,d_662,d_663,d_664,d_665,d_666,d_667,d_668,d_669,d_670,d_671,d_672,d_673,d_674,d_675,d_676,d_677,d_678,d_679,d_680,d_681,d_682,d_683,d_684,d_685,d_686,d_687,d_688,d_689,d_690,d_691,d_692,d_693,d_694,d_695,d_696,d_697,d_698,d_699,d_700,d_701,d_702,d_703,d_704,d_705,d_706,d_707,d_708,d_709,d_710,d_711,d_712,d_713,d_714,d_715,d_716,d_717,d_718,d_719,d_720,d_721,d_722,d_723,d_724,d_725,d_726,d_727,d_728,d_729,d_730,d_731,d_732,d_733,d_734,d_735,d_736,d_737,d_738,d_739,d_740,d_741,d_742,d_743,d_744,d_745,d_746,d_747,d_748,d_749,d_750,d_751,d_752,d_753,d_754,d_755,d_756,d_757,d_758,d_759,d_760,d_761,d_762,d_763,d_764,d_765,d_766,d_767,d_768,d_769,d_770,d_771,d_772,d_773,d_774,d_775,d_776,d_777,d_778,d_779,d_780,d_781,d_782,d_783,d_784,d_785,d_786,d_787,d_788,d_789,d_790,d_791,d_792,d_793,d_794,d_795,d_796,d_797,d_798,d_799,d_800,d_801,d_802,d_803,d_804,d_805,d_806,d_807,d_808,d_809,d_810,d_811,d_812,d_813,d_814,d_815,d_816,d_817,d_818,d_819,d_820,d_821,d_822,d_823,d_824,d_825,d_826,d_827,d_828,d_829,d_830,d_831,d_832,d_833,d_834,d_835,d_836,d_837,d_838,d_839,d_840,d_841,d_842,d_843,d_844,d_845,d_846,d_847,d_848,d_849,d_850,d_851,d_852,d_853,d_854,d_855,d_856,d_857,d_858,d_859,d_860,d_861,d_862,d_863,d_864,d_865,d_866,d_867,d_868,d_869,d_870,d_871,d_872,d_873,d_874,d_875,d_876,d_877,d_878,d_879,d_880,d_881,d_882,d_883,d_884,d_885,d_886,d_887,d_888,d_889,d_890,d_891,d_892,d_893,d_894,d_895,d_896,d_897,d_898,d_899,d_900,d_901,d_902,d_903,d_904,d_905,d_906,d_907,d_908,d_909,d_910,d_911,d_912,d_913,d_914,d_915,d_916,d_917,d_918,d_919,d_920,d_921,d_922,d_923,d_924,d_925,d_926,d_927,d_928,d_929,d_930,d_931,d_932,d_933,d_934,d_935,d_936,d_937,d_938,d_939,d_940,d_941,d_942,d_943,d_944,d_945,d_946,d_947,d_948,d_949,d_950,d_951,d_952,d_953,d_954,d_955,d_956,d_957,d_958,d_959,d_960,d_961,d_962,d_963,d_964,d_965,d_966,d_967,d_968,d_969,d_970,d_971,d_972,d_973,d_974,d_975,d_976,d_977,d_978,d_979,d_980,d_981,d_982,d_983,d_984,d_985,d_986,d_987,d_988,d_989,d_990,d_991,d_992,d_993,d_994,d_995,d_996,d_997,d_998,d_999,d_1000,d_1001,d_1002,d_1003,d_1004,d_1005,d_1006,d_1007,d_1008,d_1009,d_1010,d_1011,d_1012,d_1013,d_1014,d_1015,d_1016,d_1017,d_1018,d_1019,d_1020,d_1021,d_1022,d_1023,d_1024,d_1025,d_1026,d_1027,d_1028,d_1029,d_1030,d_1031,d_1032,d_1033,d_1034,d_1035,d_1036,d_1037,d_1038,d_1039,d_1040,d_1041,d_1042,d_1043,d_1044,d_1045,d_1046,d_1047,d_1048,d_1049,d_1050,d_1051,d_1052,d_1053,d_1054,d_1055,d_1056,d_1057,d_1058,d_1059,d_1060,d_1061,d_1062,d_1063,d_1064,d_1065,d_1066,d_1067,d_1068,d_1069,d_1070,d_1071,d_1072,d_1073,d_1074,d_1075,d_1076,d_1077,d_1078,d_1079,d_1080,d_1081,d_1082,d_1083,d_1084,d_1085,d_1086,d_1087,d_1088,d_1089,d_1090,d_1091,d_1092,d_1093,d_1094,d_1095,d_1096,d_1097,d_1098,d_1099,d_1100,d_1101,d_1102,d_1103,d_1104,d_1105,d_1106,d_1107,d_1108,d_1109,d_1110,d_1111,d_1112,d_1113,d_1114,d_1115,d_1116,d_1117,d_1118,d_1119,d_1120,d_1121,d_1122,d_1123,d_1124,d_1125,d_1126,d_1127,d_1128,d_1129,d_1130,d_1131,d_1132,d_1133,d_1134,d_1135,d_1136,d_1137,d_1138,d_1139,d_1140,d_1141,d_1142,d_1143,d_1144,d_1145,d_1146,d_1147,d_1148,d_1149,d_1150,d_1151,d_1152,d_1153,d_1154,d_1155,d_1156,d_1157,d_1158,d_1159,d_1160,d_1161,d_1162,d_1163,d_1164,d_1165,d_1166,d_1167,d_1168,d_1169,d_1170,d_1171,d_1172,d_1173,d_1174,d_1175,d_1176,d_1177,d_1178,d_1179,d_1180,d_1181,d_1182,d_1183,d_1184,d_1185,d_1186,d_1187,d_1188,d_1189,d_1190,d_1191,d_1192,d_1193,d_1194,d_1195,d_1196,d_1197,d_1198,d_1199,d_1200,d_1201,d_1202,d_1203,d_1204,d_1205,d_1206,d_1207,d_1208,d_1209,d_1210,d_1211,d_1212,d_1213,d_1214,d_1215,d_1216,d_1217,d_1218,d_1219,d_1220,d_1221,d_1222,d_1223,d_1224,d_1225,d_1226,d_1227,d_1228,d_1229,d_1230,d_1231,d_1232,d_1233,d_1234,d_1235,d_1236,d_1237,d_1238,d_1239,d_1240,d_1241,d_1242,d_1243,d_1244,d_1245,d_1246,d_1247,d_1248,d_1249,d_1250,d_1251,d_1252,d_1253,d_1254,d_1255,d_1256,d_1257,d_1258,d_1259,d_1260,d_1261,d_1262,d_1263,d_1264,d_1265,d_1266,d_1267,d_1268,d_1269,d_1270,d_1271,d_1272,d_1273,d_1274,d_1275,d_1276,d_1277,d_1278,d_1279,d_1280,d_1281,d_1282,d_1283,d_1284,d_1285,d_1286,d_1287,d_1288,d_1289,d_1290,d_1291,d_1292,d_1293,d_1294,d_1295,d_1296,d_1297,d_1298,d_1299,d_1300,d_1301,d_1302,d_1303,d_1304,d_1305,d_1306,d_1307,d_1308,d_1309,d_1310,d_1311,d_1312,d_1313,d_1314,d_1315,d_1316,d_1317,d_1318,d_1319,d_1320,d_1321,d_1322,d_1323,d_1324,d_1325,d_1326,d_1327,d_1328,d_1329,d_1330,d_1331,d_1332,d_1333,d_1334,d_1335,d_1336,d_1337,d_1338,d_1339,d_1340,d_1341,d_1342,d_1343,d_1344,d_1345,d_1346,d_1347,d_1348,d_1349,d_1350,d_1351,d_1352,d_1353,d_1354,d_1355,d_1356,d_1357,d_1358,d_1359,d_1360,d_1361,d_1362,d_1363,d_1364,d_1365,d_1366,d_1367,d_1368,d_1369,d_1370,d_1371,d_1372,d_1373,d_1374,d_1375,d_1376,d_1377,d_1378,d_1379,d_1380,d_1381,d_1382,d_1383,d_1384,d_1385,d_1386,d_1387,d_1388,d_1389,d_1390,d_1391,d_1392,d_1393,d_1394,d_1395,d_1396,d_1397,d_1398,d_1399,d_1400,d_1401,d_1402,d_1403,d_1404,d_1405,d_1406,d_1407,d_1408,d_1409,d_1410,d_1411,d_1412,d_1413,d_1414,d_1415,d_1416,d_1417,d_1418,d_1419,d_1420,d_1421,d_1422,d_1423,d_1424,d_1425,d_1426,d_1427,d_1428,d_1429,d_1430,d_1431,d_1432,d_1433,d_1434,d_1435,d_1436,d_1437,d_1438,d_1439,d_1440,d_1441,d_1442,d_1443,d_1444,d_1445,d_1446,d_1447,d_1448,d_1449,d_1450,d_1451,d_1452,d_1453,d_1454,d_1455,d_1456,d_1457,d_1458,d_1459,d_1460,d_1461,d_1462,d_1463,d_1464,d_1465,d_1466,d_1467,d_1468,d_1469,d_1470,d_1471,d_1472,d_1473,d_1474,d_1475,d_1476,d_1477,d_1478,d_1479,d_1480,d_1481,d_1482,d_1483,d_1484,d_1485,d_1486,d_1487,d_1488,d_1489,d_1490,d_1491,d_1492,d_1493,d_1494,d_1495,d_1496,d_1497,d_1498,d_1499,d_1500,d_1501,d_1502,d_1503,d_1504,d_1505,d_1506,d_1507,d_1508,d_1509,d_1510,d_1511,d_1512,d_1513,d_1514,d_1515,d_1516,d_1517,d_1518,d_1519,d_1520,d_1521,d_1522,d_1523,d_1524,d_1525,d_1526,d_1527,d_1528,d_1529,d_1530,d_1531,d_1532,d_1533,d_1534,d_1535,d_1536,d_1537,d_1538,d_1539,d_1540,d_1541,d_1542,d_1543,d_1544,d_1545,d_1546,d_1547,d_1548,d_1549,d_1550,d_1551,d_1552,d_1553,d_1554,d_1555,d_1556,d_1557,d_1558,d_1559,d_1560,d_1561,d_1562,d_1563,d_1564,d_1565,d_1566,d_1567,d_1568,d_1569,d_1570,d_1571,d_1572,d_1573,d_1574,d_1575,d_1576,d_1577,d_1578,d_1579,d_1580,d_1581,d_1582,d_1583,d_1584,d_1585,d_1586,d_1587,d_1588,d_1589,d_1590,d_1591,d_1592,d_1593,d_1594,d_1595,d_1596,d_1597,d_1598,d_1599,d_1600,d_1601,d_1602,d_1603,d_1604,d_1605,d_1606,d_1607,d_1608,d_1609,d_1610,d_1611,d_1612,d_1613,d_1614,d_1615,d_1616,d_1617,d_1618,d_1619,d_1620,d_1621,d_1622,d_1623,d_1624,d_1625,d_1626,d_1627,d_1628,d_1629,d_1630,d_1631,d_1632,d_1633,d_1634,d_1635,d_1636,d_1637,d_1638,d_1639,d_1640,d_1641,d_1642,d_1643,d_1644,d_1645,d_1646,d_1647,d_1648,d_1649,d_1650,d_1651,d_1652,d_1653,d_1654,d_1655,d_1656,d_1657,d_1658,d_1659,d_1660,d_1661,d_1662,d_1663,d_1664,d_1665,d_1666,d_1667,d_1668,d_1669,d_1670,d_1671,d_1672,d_1673,d_1674,d_1675,d_1676,d_1677,d_1678,d_1679,d_1680,d_1681,d_1682,d_1683,d_1684,d_1685,d_1686,d_1687,d_1688,d_1689,d_1690,d_1691,d_1692,d_1693,d_1694,d_1695,d_1696,d_1697,d_1698,d_1699,d_1700,d_1701,d_1702,d_1703,d_1704,d_1705,d_1706,d_1707,d_1708,d_1709,d_1710,d_1711,d_1712,d_1713,d_1714,d_1715,d_1716,d_1717,d_1718,d_1719,d_1720,d_1721,d_1722,d_1723,d_1724,d_1725,d_1726,d_1727,d_1728,d_1729,d_1730,d_1731,d_1732,d_1733,d_1734,d_1735,d_1736,d_1737,d_1738,d_1739,d_1740,d_1741,d_1742,d_1743,d_1744,d_1745,d_1746,d_1747,d_1748,d_1749,d_1750,d_1751,d_1752,d_1753,d_1754,d_1755,d_1756,d_1757,d_1758,d_1759,d_1760,d_1761,d_1762,d_1763,d_1764,d_1765,d_1766,d_1767,d_1768,d_1769,d_1770,d_1771,d_1772,d_1773,d_1774,d_1775,d_1776,d_1777,d_1778,d_1779,d_1780,d_1781,d_1782,d_1783,d_1784,d_1785,d_1786,d_1787,d_1788,d_1789,d_1790,d_1791,d_1792,d_1793,d_1794,d_1795,d_1796,d_1797,d_1798,d_1799,d_1800,d_1801,d_1802,d_1803,d_1804,d_1805,d_1806,d_1807,d_1808,d_1809,d_1810,d_1811,d_1812,d_1813,d_1814,d_1815,d_1816,d_1817,d_1818,d_1819,d_1820,d_1821,d_1822,d_1823,d_1824,d_1825,d_1826,d_1827,d_1828,d_1829,d_1830,d_1831,d_1832,d_1833,d_1834,d_1835,d_1836,d_1837,d_1838,d_1839,d_1840,d_1841,d_1842,d_1843,d_1844,d_1845,d_1846,d_1847,d_1848,d_1849,d_1850,d_1851,d_1852,d_1853,d_1854,d_1855,d_1856,d_1857,d_1858,d_1859,d_1860,d_1861,d_1862,d_1863,d_1864,d_1865,d_1866,d_1867,d_1868,d_1869,d_1870,d_1871,d_1872,d_1873,d_1874,d_1875,d_1876,d_1877,d_1878,d_1879,d_1880,d_1881,d_1882,d_1883,d_1884,d_1885,d_1886,d_1887,d_1888,d_1889,d_1890,d_1891,d_1892,d_1893,d_1894,d_1895,d_1896,d_1897,d_1898,d_1899,d_1900,d_1901,d_1902,d_1903,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,1,1,0,0,0,0,0,1,2,1,0,1,1,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,2,1,0,0,0,2,0,0,0,0,0,1,0,0,0,1,0,1,2,1,1,0,0,0,0,1,0,0,1,2,0,1,0,0,1,0,1,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,2,2,0,1,1,0,0,0,1,1,0,1,1,1,1,0,2,3,1,1,0,0,0,0,0,1,0,0,0,0,2,1,0,0,1,1,2,1,1,0,1,0,1,1,0,1,1,0,3,0,0,3,0,1,1,2,0,1,1,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,2,0,0,1,0,2,0,0,0,0,0,0,1,0,1,0,1,1,0,0,0,0,0,1,0,0,0,0,0,1,2,0,0,0,0,0,0,1,2,0,0,0,2,1,2,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,1,1,0,2,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,0,0,1,1,2,0,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,2,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0,1,0,1,0,0,1,0,0,1,1,2,0,1,0,0,0,0,0,0,0,0,3,1,2,2,1,1,0,0,2,0,0,0,0,1,0,1,0,0,0,1,1,0,3,1,0,0,0,0,0,1,0,1,1,1,0,0,0,0,2,0,0,2,0,0,0,1,0,0,0,0,0,4,0,0,2,1,0,0,0,0,0,1,0,0,0,0,0,4,0,1,0,1,2,2,0,0,0,0,2,1,1,1,1,1,0,0,1,0,0,1,0,0,0,1,1,0,1,2,0,0,2,0,1,3,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,1,1,0,1,1,0,0,1,1,1,0,0,0,0,0,2,0,0,0,0,3,0,2,0,0,0,0,3,2,0,2,0,0,2,0,0,0,0,3,0,1,1,1,0,1,0,1,0,0,2,4,0,0,0,0,0,2,0,0,1,0,0,1,1,5,1,1,0,0,0,0,0,0,0,0,2,1,1,0,2,0,2,1,0,1,0,1,1,0,0,0,2,1,1,0,0,1,0,3,0,0,0,1,0,0,2,1,0,1,0,0,3,3,0,0,0,0,0,0,0,1,1,1,0,2,2,2,0,0,1,0,0,1,3,0,0,0,1,1,0,1,0,1,0,0,1,1,1,2,1,1,1,0,2,2,2,1,0,0,0,1,2,0,0,1,2,1,1,1,0,1,0,1,0,0,1,0,1,0,2,1,0,2,0,1,0,0,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,3,1,1,0,1,1,0,0,0,1,1,2,0,0,0,1,0,2,1,0,1,1,0,0,0,1,1,1,3,1,1,0,0,2,0,1,0,0,0,2,0,0,0,4,2,1,0,0,0,0,2,1,0,1,1,0,0,0,1,2,1,1,0,0,2,0,2,2,0,0,0,1,1,0,2,0,1,1,2,0,1,0,0,0,2,1,0,1,1,2,0,0,0,0,0,0,0,1,0,1,0,1,0,3,1,1,0,1,1,2,0,0,0,0,1,1,0,0,0,0,3,0,1,0,0,0,0,1,1,1,0,1,0,2,0,0,0,0,2,0,0,0,0,1,1,2,0,0,0,0,2,0,0,1,1,1,1,0,0,0,0,0,1,2,2,0,1,0,0,0,0,1,2,1,0,0,0,0,0,1,0,3,0,1,2,1,0,3,0,0,0,1,0,2,2,1,0,0,1,2,0,1,0,1,4,0,0,5,0,0,0,0,0,0,2,1,2,1,0,0,0,1,1,1,0,0,1,1,1,1,1,0,0,0,2,2,0,0,1,4,0,0,0,0,1,1,2,0,4,0,1,0,1,4,2,0,2,0,1,1,0,1,0,0,1,1,3,0,0,0,1,1,1,3,1,3,1,2,2,0,1,1,1,1,0,0,0,0,0,1,0,4,2,3,0,1,2,0,0,0,1,1,3,0,1,1,1,3,0,1,1

Rows : 30490
Columns : 1919

# 📊 Source Data Understanding

This section examines each raw dataset to understand:

- Structure
- Dimensions
- Data Types
- Missing Values
- Business Purpose

A thorough understanding of the source data ensures accurate data engineering and prevents errors during integration.

In [79]:
# ============================================================
# Sales Dataset Information
# ============================================================

print("=" * 70)
print("SALES DATASET INFORMATION")
print("=" * 70)

sales_df.info()

print("\nMissing Values")
display(sales_df.isnull().sum().sort_values(ascending=False).head(10))

print("\nStatistical Summary")
display(sales_df.describe())

======================================================================
SALES DATASET INFORMATION
======================================================================
<class 'pandas.DataFrame'>
RangeIndex: 30490 entries, 0 to 30489
Columns: 1919 entries, id to d_1913
dtypes: int64(1913), str(6)
memory usage: 448.2 MB

Missing Values

id          0
item_id     0
dept_id     0
cat_id      0
store_id    0
state_id    0
d_1         0
d_2         0
d_3         0
d_4         0
dtype: int64

Statistical Summary

,d_1,d_2,d_3,d_4,d_5,d_6,d_7,d_8,d_9,d_10,d_11,d_12,d_13,d_14,d_15,d_16,d_17,d_18,d_19,d_20,d_21,d_22,d_23,d_24,d_25,d_26,d_27,d_28,d_29,d_30,d_31,d_32,d_33,d_34,d_35,d_36,d_37,d_38,d_39,d_40,d_41,d_42,d_43,d_44,d_45,d_46,d_47,d_48,d_49,d_50,d_51,d_52,d_53,d_54,d_55,d_56,d_57,d_58,d_59,d_60,d_61,d_62,d_63,d_64,d_65,d_66,d_67,d_68,d_69,d_70,d_71,d_72,d_73,d_74,d_75,d_76,d_77,d_78,d_79,d_80,d_81,d_82,d_83,d_84,d_85,d_86,d_87,d_88,d_89,d_90,d_91,d_92,d_93,d_94,d_95,d_96,d_97,d_98,d_99,d_100,d_101,d_102,d_103,d_104,d_105,d_106,d_107,d_108,d_109,d_110,d_111,d_112,d_113,d_114,d_115,d_116,d_117,d_118,d_119,d_120,d_121,d_122,d_123,d_124,d_125,d_126,d_127,d_128,d_129,d_130,d_131,d_132,d_133,d_134,d_135,d_136,d_137,d_138,d_139,d_140,d_141,d_142,d_143,d_144,d_145,d_146,d_147,d_148,d_149,d_150,d_151,d_152,d_153,d_154,d_155,d_156,d_157,d_158,d_159,d_160,d_161,d_162,d_163,d_164,d_165,d_166,d_167,d_168,d_169,d_170,d_171,d_172,d_173,d_174,d_175,d_176,d_177,d_178,d_179,d_180,d_181,d_182,d_183,d_184,d_185,d_186,d_187,d_188,d_189,d_190,d_191,d_192,d_193,d_194,d_195,d_196,d_197,d_198,d_199,d_200,d_201,d_202,d_203,d_204,d_205,d_206,d_207,d_208,d_209,d_210,d_211,d_212,d_213,d_214,d_215,d_216,d_217,d_218,d_219,d_220,d_221,d_222,d_223,d_224,d_225,d_226,d_227,d_228,d_229,d_230,d_231,d_232,d_233,d_234,d_235,d_236,d_237,d_238,d_239,d_240,d_241,d_242,d_243,d_244,d_245,d_246,d_247,d_248,d_249,d_250,d_251,d_252,d_253,d_254,d_255,d_256,d_257,d_258,d_259,d_260,d_261,d_262,d_263,d_264,d_265,d_266,d_267,d_268,d_269,d_270,d_271,d_272,d_273,d_274,d_275,d_276,d_277,d_278,d_279,d_280,d_281,d_282,d_283,d_284,d_285,d_286,d_287,d_288,d_289,d_290,d_291,d_292,d_293,d_294,d_295,d_296,d_297,d_298,d_299,d_300,d_301,d_302,d_303,d_304,d_305,d_306,d_307,d_308,d_309,d_310,d_311,d_312,d_313,d_314,d_315,d_316,d_317,d_318,d_319,d_320,d_321,d_322,d_323,d_324,d_325,d_326,d_327,d_328,d_329,d_330,d_331,d_332,d_333,d_334,d_335,d_336,d_337,d_338,d_339,d_340,d_341,d_342,d_343,d_344,d_345,d_346,d_347,d_348,d_349,d_350,d_351,d_352,d_353,d_354,d_355,d_356,d_357,d_358,d_359,d_360,d_361,d_362,d_363,d_364,d_365,d_366,d_367,d_368,d_369,d_370,d_371,d_372,d_373,d_374,d_375,d_376,d_377,d_378,d_379,d_380,d_381,d_382,d_383,d_384,d_385,d_386,d_387,d_388,d_389,d_390,d_391,d_392,d_393,d_394,d_395,d_396,d_397,d_398,d_399,d_400,d_401,d_402,d_403,d_404,d_405,d_406,d_407,d_408,d_409,d_410,d_411,d_412,d_413,d_414,d_415,d_416,d_417,d_418,d_419,d_420,d_421,d_422,d_423,d_424,d_425,d_426,d_427,d_428,d_429,d_430,d_431,d_432,d_433,d_434,d_435,d_436,d_437,d_438,d_439,d_440,d_441,d_442,d_443,d_444,d_445,d_446,d_447,d_448,d_449,d_450,d_451,d_452,d_453,d_454,d_455,d_456,d_457,d_458,d_459,d_460,d_461,d_462,d_463,d_464,d_465,d_466,d_467,d_468,d_469,d_470,d_471,d_472,d_473,d_474,d_475,d_476,d_477,d_478,d_479,d_480,d_481,d_482,d_483,d_484,d_485,d_486,d_487,d_488,d_489,d_490,d_491,d_492,d_493,d_494,d_495,d_496,d_497,d_498,d_499,d_500,d_501,d_502,d_503,d_504,d_505,d_506,d_507,d_508,d_509,d_510,d_511,d_512,d_513,d_514,d_515,d_516,d_517,d_518,d_519,d_520,d_521,d_522,d_523,d_524,d_525,d_526,d_527,d_528,d_529,d_530,d_531,d_532,d_533,d_534,d_535,d_536,d_537,d_538,d_539,d_540,d_541,d_542,d_543,d_544,d_545,d_546,d_547,d_548,d_549,d_550,d_551,d_552,d_553,d_554,d_555,d_556,d_557,d_558,d_559,d_560,d_561,d_562,d_563,d_564,d_565,d_566,d_567,d_568,d_569,d_570,d_571,d_572,d_573,d_574,d_575,d_576,d_577,d_578,d_579,d_580,d_581,d_582,d_583,d_584,d_585,d_586,d_587,d_588,d_589,d_590,d_591,d_592,d_593,d_594,d_595,d_596,d_597,d_598,d_599,d_600,d_601,d_602,d_603,d_604,d_605,d_606,d_607,d_608,d_609,d_610,d_611,d_612,d_613,d_614,d_615,d_616,d_617,d_618,d_619,d_620,d_621,d_622,d_623,d_624,d_625,d_626,d_627,d_628,d_629,d_630,d_631,d_632,d_633,d_634,d_635,d_636,d_637,d_638,d_639,d_640,d_641,d_642,d_643,d_644,d_645,d_646,d_647,d_648,d_649,d_650,d_651,d_652,d_653,d_654,d_655,d_656,d_657,d_658,d_659,d_660,d_661,d_662,d_663,d_664,d_665,d_666,d_667,d_668,d_669,d_670,d_671,d_672,d_673,d_674,d_675,d_676,d_677,d_678,d_679,d_680,d_681,d_682,d_683,d_684,d_685,d_686,d_687,d_688,d_689,d_690,d_691,d_692,d_693,d_694,d_695,d_696,d_697,d_698,d_699,d_700,d_701,d_702,d_703,d_704,d_705,d_706,d_707,d_708,d_709,d_710,d_711,d_712,d_713,d_714,d_715,d_716,d_717,d_718,d_719,d_720,d_721,d_722,d_723,d_724,d_725,d_726,d_727,d_728,d_729,d_730,d_731,d_732,d_733,d_734,d_735,d_736,d_737,d_738,d_739,d_740,d_741,d_742,d_743,d_744,d_745,d_746,d_747,d_748,d_749,d_750,d_751,d_752,d_753,d_754,d_755,d_756,d_757,d_758,d_759,d_760,d_761,d_762,d_763,d_764,d_765,d_766,d_767,d_768,d_769,d_770,d_771,d_772,d_773,d_774,d_775,d_776,d_777,d_778,d_779,d_780,d_781,d_782,d_783,d_784,d_785,d_786,d_787,d_788,d_789,d_790,d_791,d_792,d_793,d_794,d_795,d_796,d_797,d_798,d_799,d_800,d_801,d_802,d_803,d_804,d_805,d_806,d_807,d_808,d_809,d_810,d_811,d_812,d_813,d_814,d_815,d_816,d_817,d_818,d_819,d_820,d_821,d_822,d_823,d_824,d_825,d_826,d_827,d_828,d_829,d_830,d_831,d_832,d_833,d_834,d_835,d_836,d_837,d_838,d_839,d_840,d_841,d_842,d_843,d_844,d_845,d_846,d_847,d_848,d_849,d_850,d_851,d_852,d_853,d_854,d_855,d_856,d_857,d_858,d_859,d_860,d_861,d_862,d_863,d_864,d_865,d_866,d_867,d_868,d_869,d_870,d_871,d_872,d_873,d_874,d_875,d_876,d_877,d_878,d_879,d_880,d_881,d_882,d_883,d_884,d_885,d_886,d_887,d_888,d_889,d_890,d_891,d_892,d_893,d_894,d_895,d_896,d_897,d_898,d_899,d_900,d_901,d_902,d_903,d_904,d_905,d_906,d_907,d_908,d_909,d_910,d_911,d_912,d_913,d_914,d_915,d_916,d_917,d_918,d_919,d_920,d_921,d_922,d_923,d_924,d_925,d_926,d_927,d_928,d_929,d_930,d_931,d_932,d_933,d_934,d_935,d_936,d_937,d_938,d_939,d_940,d_941,d_942,d_943,d_944,d_945,d_946,d_947,d_948,d_949,d_950,d_951,d_952,d_953,d_954,d_955,d_956,d_957,d_958,d_959,d_960,d_961,d_962,d_963,d_964,d_965,d_966,d_967,d_968,d_969,d_970,d_971,d_972,d_973,d_974,d_975,d_976,d_977,d_978,d_979,d_980,d_981,d_982,d_983,d_984,d_985,d_986,d_987,d_988,d_989,d_990,d_991,d_992,d_993,d_994,d_995,d_996,d_997,d_998,d_999,d_1000,d_1001,d_1002,d_1003,d_1004,d_1005,d_1006,d_1007,d_1008,d_1009,d_1010,d_1011,d_1012,d_1013,d_1014,d_1015,d_1016,d_1017,d_1018,d_1019,d_1020,d_1021,d_1022,d_1023,d_1024,d_1025,d_1026,d_1027,d_1028,d_1029,d_1030,d_1031,d_1032,d_1033,d_1034,d_1035,d_1036,d_1037,d_1038,d_1039,d_1040,d_1041,d_1042,d_1043,d_1044,d_1045,d_1046,d_1047,d_1048,d_1049,d_1050,d_1051,d_1052,d_1053,d_1054,d_1055,d_1056,d_1057,d_1058,d_1059,d_1060,d_1061,d_1062,d_1063,d_1064,d_1065,d_1066,d_1067,d_1068,d_1069,d_1070,d_1071,d_1072,d_1073,d_1074,d_1075,d_1076,d_1077,d_1078,d_1079,d_1080,d_1081,d_1082,d_1083,d_1084,d_1085,d_1086,d_1087,d_1088,d_1089,d_1090,d_1091,d_1092,d_1093,d_1094,d_1095,d_1096,d_1097,d_1098,d_1099,d_1100,d_1101,d_1102,d_1103,d_1104,d_1105,d_1106,d_1107,d_1108,d_1109,d_1110,d_1111,d_1112,d_1113,d_1114,d_1115,d_1116,d_1117,d_1118,d_1119,d_1120,d_1121,d_1122,d_1123,d_1124,d_1125,d_1126,d_1127,d_1128,d_1129,d_1130,d_1131,d_1132,d_1133,d_1134,d_1135,d_1136,d_1137,d_1138,d_1139,d_1140,d_1141,d_1142,d_1143,d_1144,d_1145,d_1146,d_1147,d_1148,d_1149,d_1150,d_1151,d_1152,d_1153,d_1154,d_1155,d_1156,d_1157,d_1158,d_1159,d_1160,d_1161,d_1162,d_1163,d_1164,d_1165,d_1166,d_1167,d_1168,d_1169,d_1170,d_1171,d_1172,d_1173,d_1174,d_1175,d_1176,d_1177,d_1178,d_1179,d_1180,d_1181,d_1182,d_1183,d_1184,d_1185,d_1186,d_1187,d_1188,d_1189,d_1190,d_1191,d_1192,d_1193,d_1194,d_1195,d_1196,d_1197,d_1198,d_1199,d_1200,d_1201,d_1202,d_1203,d_1204,d_1205,d_1206,d_1207,d_1208,d_1209,d_1210,d_1211,d_1212,d_1213,d_1214,d_1215,d_1216,d_1217,d_1218,d_1219,d_1220,d_1221,d_1222,d_1223,d_1224,d_1225,d_1226,d_1227,d_1228,d_1229,d_1230,d_1231,d_1232,d_1233,d_1234,d_1235,d_1236,d_1237,d_1238,d_1239,d_1240,d_1241,d_1242,d_1243,d_1244,d_1245,d_1246,d_1247,d_1248,d_1249,d_1250,d_1251,d_1252,d_1253,d_1254,d_1255,d_1256,d_1257,d_1258,d_1259,d_1260,d_1261,d_1262,d_1263,d_1264,d_1265,d_1266,d_1267,d_1268,d_1269,d_1270,d_1271,d_1272,d_1273,d_1274,d_1275,d_1276,d_1277,d_1278,d_1279,d_1280,d_1281,d_1282,d_1283,d_1284,d_1285,d_1286,d_1287,d_1288,d_1289,d_1290,d_1291,d_1292,d_1293,d_1294,d_1295,d_1296,d_1297,d_1298,d_1299,d_1300,d_1301,d_1302,d_1303,d_1304,d_1305,d_1306,d_1307,d_1308,d_1309,d_1310,d_1311,d_1312,d_1313,d_1314,d_1315,d_1316,d_1317,d_1318,d_1319,d_1320,d_1321,d_1322,d_1323,d_1324,d_1325,d_1326,d_1327,d_1328,d_1329,d_1330,d_1331,d_1332,d_1333,d_1334,d_1335,d_1336,d_1337,d_1338,d_1339,d_1340,d_1341,d_1342,d_1343,d_1344,d_1345,d_1346,d_1347,d_1348,d_1349,d_1350,d_1351,d_1352,d_1353,d_1354,d_1355,d_1356,d_1357,d_1358,d_1359,d_1360,d_1361,d_1362,d_1363,d_1364,d_1365,d_1366,d_1367,d_1368,d_1369,d_1370,d_1371,d_1372,d_1373,d_1374,d_1375,d_1376,d_1377,d_1378,d_1379,d_1380,d_1381,d_1382,d_1383,d_1384,d_1385,d_1386,d_1387,d_1388,d_1389,d_1390,d_1391,d_1392,d_1393,d_1394,d_1395,d_1396,d_1397,d_1398,d_1399,d_1400,d_1401,d_1402,d_1403,d_1404,d_1405,d_1406,d_1407,d_1408,d_1409,d_1410,d_1411,d_1412,d_1413,d_1414,d_1415,d_1416,d_1417,d_1418,d_1419,d_1420,d_1421,d_1422,d_1423,d_1424,d_1425,d_1426,d_1427,d_1428,d_1429,d_1430,d_1431,d_1432,d_1433,d_1434,d_1435,d_1436,d_1437,d_1438,d_1439,d_1440,d_1441,d_1442,d_1443,d_1444,d_1445,d_1446,d_1447,d_1448,d_1449,d_1450,d_1451,d_1452,d_1453,d_1454,d_1455,d_1456,d_1457,d_1458,d_1459,d_1460,d_1461,d_1462,d_1463,d_1464,d_1465,d_1466,d_1467,d_1468,d_1469,d_1470,d_1471,d_1472,d_1473,d_1474,d_1475,d_1476,d_1477,d_1478,d_1479,d_1480,d_1481,d_1482,d_1483,d_1484,d_1485,d_1486,d_1487,d_1488,d_1489,d_1490,d_1491,d_1492,d_1493,d_1494,d_1495,d_1496,d_1497,d_1498,d_1499,d_1500,d_1501,d_1502,d_1503,d_1504,d_1505,d_1506,d_1507,d_1508,d_1509,d_1510,d_1511,d_1512,d_1513,d_1514,d_1515,d_1516,d_1517,d_1518,d_1519,d_1520,d_1521,d_1522,d_1523,d_1524,d_1525,d_1526,d_1527,d_1528,d_1529,d_1530,d_1531,d_1532,d_1533,d_1534,d_1535,d_1536,d_1537,d_1538,d_1539,d_1540,d_1541,d_1542,d_1543,d_1544,d_1545,d_1546,d_1547,d_1548,d_1549,d_1550,d_1551,d_1552,d_1553,d_1554,d_1555,d_1556,d_1557,d_1558,d_1559,d_1560,d_1561,d_1562,d_1563,d_1564,d_1565,d_1566,d_1567,d_1568,d_1569,d_1570,d_1571,d_1572,d_1573,d_1574,d_1575,d_1576,d_1577,d_1578,d_1579,d_1580,d_1581,d_1582,d_1583,d_1584,d_1585,d_1586,d_1587,d_1588,d_1589,d_1590,d_1591,d_1592,d_1593,d_1594,d_1595,d_1596,d_1597,d_1598,d_1599,d_1600,d_1601,d_1602,d_1603,d_1604,d_1605,d_1606,d_1607,d_1608,d_1609,d_1610,d_1611,d_1612,d_1613,d_1614,d_1615,d_1616,d_1617,d_1618,d_1619,d_1620,d_1621,d_1622,d_1623,d_1624,d_1625,d_1626,d_1627,d_1628,d_1629,d_1630,d_1631,d_1632,d_1633,d_1634,d_1635,d_1636,d_1637,d_1638,d_1639,d_1640,d_1641,d_1642,d_1643,d_1644,d_1645,d_1646,d_1647,d_1648,d_1649,d_1650,d_1651,d_1652,d_1653,d_1654,d_1655,d_1656,d_1657,d_1658,d_1659,d_1660,d_1661,d_1662,d_1663,d_1664,d_1665,d_1666,d_1667,d_1668,d_1669,d_1670,d_1671,d_1672,d_1673,d_1674,d_1675,d_1676,d_1677,d_1678,d_1679,d_1680,d_1681,d_1682,d_1683,d_1684,d_1685,d_1686,d_1687,d_1688,d_1689,d_1690,d_1691,d_1692,d_1693,d_1694,d_1695,d_1696,d_1697,d_1698,d_1699,d_1700,d_1701,d_1702,d_1703,d_1704,d_1705,d_1706,d_1707,d_1708,d_1709,d_1710,d_1711,d_1712,d_1713,d_1714,d_1715,d_1716,d_1717,d_1718,d_1719,d_1720,d_1721,d_1722,d_1723,d_1724,d_1725,d_1726,d_1727,d_1728,d_1729,d_1730,d_1731,d_1732,d_1733,d_1734,d_1735,d_1736,d_1737,d_1738,d_1739,d_1740,d_1741,d_1742,d_1743,d_1744,d_1745,d_1746,d_1747,d_1748,d_1749,d_1750,d_1751,d_1752,d_1753,d_1754,d_1755,d_1756,d_1757,d_1758,d_1759,d_1760,d_1761,d_1762,d_1763,d_1764,d_1765,d_1766,d_1767,d_1768,d_1769,d_1770,d_1771,d_1772,d_1773,d_1774,d_1775,d_1776,d_1777,d_1778,d_1779,d_1780,d_1781,d_1782,d_1783,d_1784,d_1785,d_1786,d_1787,d_1788,d_1789,d_1790,d_1791,d_1792,d_1793,d_1794,d_1795,d_1796,d_1797,d_1798,d_1799,d_1800,d_1801,d_1802,d_1803,d_1804,d_1805,d_1806,d_1807,d_1808,d_1809,d_1810,d_1811,d_1812,d_1813,d_1814,d_1815,d_1816,d_1817,d_1818,d_1819,d_1820,d_1821,d_1822,d_1823,d_1824,d_1825,d_1826,d_1827,d_1828,d_1829,d_1830,d_1831,d_1832,d_1833,d_1834,d_1835,d_1836,d_1837,d_1838,d_1839,d_1840,d_1841,d_1842,d_1843,d_1844,d_1845,d_1846,d_1847,d_1848,d_1849,d_1850,d_1851,d_1852,d_1853,d_1854,d_1855,d_1856,d_1857,d_1858,d_1859,d_1860,d_1861,d_1862,d_1863,d_1864,d_1865,d_1866,d_1867,d_1868,d_1869,d_1870,d_1871,d_1872,d_1873,d_1874,d_1875,d_1876,d_1877,d_1878,d_1879,d_1880,d_1881,d_1882,d_1883,d_1884,d_1885,d_1886,d_1887,d_1888,d_1889,d_1890,d_1891,d_1892,d_1893,d_1894,d_1895,d_1896,d_1897,d_1898,d_1899,d_1900,d_1901,d_1902,d_1903,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913

In [80]:
# ============================================================
# Calendar Dataset Information
# ============================================================

print("=" * 70)
print("CALENDAR DATASET INFORMATION")
print("=" * 70)

calendar_df.info()

print("\nMissing Values")
display(calendar_df.isnull().sum().sort_values(ascending=False))

print("\nStatistical Summary")
display(calendar_df.describe(include="all"))

======================================================================
CALENDAR DATASET INFORMATION
======================================================================
<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1969 non-null   str
 1   wm_yr_wk      1969 non-null   int64
 2   weekday       1969 non-null   str
 3   wday          1969 non-null   int64
 4   month         1969 non-null   int64
 5   year          1969 non-null   int64
 6   d             1969 non-null   str
 7   event_name_1  162 non-null    str
 8   event_type_1  162 non-null    str
 9   event_name_2  5 non-null      str
 10  event_type_2  5 non-null      str
 11  snap_CA       1969 non-null   int64
 12  snap_TX       1969 non-null   int64
 13  snap_WI       1969 non-null   int64
dtypes: int64(7), str(7)
memory usage: 263.1 KB

Missing Values

event_type_2    1964
event_name_2    1964
event_name_1    1807
event_type_1    1807
date               0
wm_yr_wk           0
year               0
month              0
wday               0
weekday            0
d                  0
snap_CA            0
snap_TX            0
snap_WI            0
dtype: int64

Statistical Summary

              date  wm_yr_wk   weekday    wday   month    year     d event_name_1 event_type_1  event_name_2 event_type_2  snap_CA  snap_TX  snap_WI
count         1969   1969.00      1969 1969.00 1969.00 1969.00  1969          162          162             5            5  1969.00  1969.00  1969.00
unique        1969       NaN         7     NaN     NaN     NaN  1969           30            4             4            2      NaN      NaN      NaN
top     2011-01-29       NaN  Saturday     NaN     NaN     NaN   d_1    SuperBowl    Religious  Father's day     Cultural      NaN      NaN      NaN
freq             1       NaN       282     NaN     NaN     NaN     1            6           55             2            4      NaN      NaN      NaN
mean           NaN  11347.09       NaN    4.00    6.33 2013.29   NaN          NaN          NaN           NaN          NaN     0.33     0.33     0.33
std            NaN    155.28       NaN    2.00    3.42    1.58   NaN          NaN          NaN           NaN          NaN     0.47     0.47     0.47
min            NaN  11101.00       NaN    1.00    1.00 2011.00   NaN          NaN          NaN           NaN          NaN     0.00     0.00     0.00
25%            NaN  11219.00       NaN    2.00    3.00 2012.00   NaN          NaN          NaN           NaN          NaN     0.00     0.00     0.00
50%            NaN  11337.00       NaN    4.00    6.00 2013.00   NaN          NaN          NaN           NaN          NaN     0.00     0.00     0.00
75%            NaN  11502.00       NaN    6.00    9.00 2015.00   NaN          NaN          NaN           NaN          NaN     1.00     1.00     1.00
max            NaN  11621.00       NaN    7.00   12.00 2016.00   NaN          NaN          NaN           NaN          NaN     1.00     1.00     1.00

In [81]:
# ============================================================
# Prices Dataset Information
# ============================================================

print("=" * 70)
print("SELLING PRICES DATASET INFORMATION")
print("=" * 70)

prices_df.info()

print("\nMissing Values")
display(prices_df.isnull().sum().sort_values(ascending=False))

print("\nStatistical Summary")
display(prices_df.describe(include="all"))

======================================================================
SELLING PRICES DATASET INFORMATION
======================================================================
<class 'pandas.DataFrame'>
RangeIndex: 6841121 entries, 0 to 6841120
Data columns (total 4 columns):
 #   Column      Dtype
---  ------      -----
 0   store_id    str
 1   item_id     str
 2   wm_yr_wk    int64
 3   sell_price  float64
dtypes: float64(1), int64(1), str(2)
memory usage: 318.1 MB

Missing Values

store_id      0
item_id       0
wm_yr_wk      0
sell_price    0
dtype: int64

Statistical Summary

       store_id        item_id   wm_yr_wk  sell_price
count   6841121        6841121 6841121.00  6841121.00
unique       10           3049        NaN         NaN
top        TX_2  HOBBIES_1_010        NaN         NaN
freq     701214           2820        NaN         NaN
mean        NaN            NaN   11382.94        4.41
std         NaN            NaN     148.61        3.41
min         NaN            NaN   11101.00        0.01
25%         NaN            NaN   11247.00        2.18
50%         NaN            NaN   11411.00        3.47
75%         NaN            NaN   11517.00        5.84
max         NaN            NaN   11621.00      107.32

# 📋 Dataset Summary

## Sales Dataset

Contains historical daily unit sales for each product across different stores.

**Primary Key**

- item_id
- store_id

---

## Calendar Dataset

Maps each day to calendar events, SNAP eligibility, weekdays, months, and years.

Used for creating time-based forecasting features.

---

## Selling Prices Dataset

Contains weekly selling prices for each product-store combination.

Used for revenue estimation and price-related feature engineering.

# 🧹 Data Quality Assessment

Before cleaning the datasets, we evaluate their quality by checking:

- Missing values
- Duplicate records
- Data types
- Invalid values
- Dataset consistency

These checks help identify issues that could affect downstream analysis and machine learning models.

In [82]:
# ============================================================
# Missing Values Report
# ============================================================

def missing_report(df, name):
    report = (
        df.isnull()
          .sum()
          .to_frame(name="Missing Values")
    )

    report["Percentage"] = (
        report["Missing Values"] / len(df)
    ) * 100

    report = report[report["Missing Values"] > 0]

    print(f"\n{name}")
    print("-" * 50)

    if report.empty:
        print("✅ No missing values found.")
    else:
        display(report.sort_values("Missing Values", ascending=False))


missing_report(sales_df, "Sales Dataset")
missing_report(calendar_df, "Calendar Dataset")
missing_report(prices_df, "Prices Dataset")

Sales Dataset
--------------------------------------------------
✅ No missing values found.

Calendar Dataset
--------------------------------------------------

              Missing Values  Percentage
event_type_2            1964       99.75
event_name_2            1964       99.75
event_type_1            1807       91.77
event_name_1            1807       91.77

Prices Dataset
--------------------------------------------------
✅ No missing values found.

In [83]:
# ============================================================
# Duplicate Records
# ============================================================

print("Duplicate Rows\n")

print(f"Sales Dataset     : {sales_df.duplicated().sum()}")

print(f"Calendar Dataset  : {calendar_df.duplicated().sum()}")

print(f"Prices Dataset    : {prices_df.duplicated().sum()}")

Duplicate Rows

Sales Dataset     : 0
Calendar Dataset  : 0
Prices Dataset    : 0

In [84]:
# ============================================================
# Data Types Summary
# ============================================================

print("Sales Dataset")
display(sales_df.dtypes.value_counts())

print("\nCalendar Dataset")
display(calendar_df.dtypes.value_counts())

print("\nPrices Dataset")
display(prices_df.dtypes.value_counts())

Sales Dataset

int64    1913
str         6
Name: count, dtype: int64

Calendar Dataset

str      7
int64    7
Name: count, dtype: int64

Prices Dataset

str        2
int64      1
float64    1
Name: count, dtype: int64

In [85]:
# ============================================================
# Memory Usage
# ============================================================

def memory_usage(df, name):
    mem = df.memory_usage(deep=True).sum() / 1024**2
    print(f"{name}: {mem:.2f} MB")


memory_usage(sales_df, "Sales Dataset")
memory_usage(calendar_df, "Calendar Dataset")
memory_usage(prices_df, "Prices Dataset")

Sales Dataset: 448.23 MB
Calendar Dataset: 0.26 MB
Prices Dataset: 318.15 MB

# 🧹 Data Quality Assessment

High-quality data is essential for accurate analytics and forecasting.

In this section, we assess the quality of the raw datasets by examining:

- Dataset dimensions
- Missing values
- Duplicate records
- Data types
- Memory usage

These checks help identify potential issues before data cleaning and integration.

In [86]:
# ============================================================
# Dataset Overview Function
# ============================================================

def dataset_overview(df, name):
    """Display basic information about a dataset."""
    
    print("=" * 80)
    print(f"{name.upper()}")
    print("=" * 80)
    
    print(f"Rows    : {df.shape[0]:,}")
    print(f"Columns : {df.shape[1]:,}")
    print(f"Memory  : {df.memory_usage(deep=True).sum() / 1024**2:.2f} MB")
    
    print("\nData Types")
    display(df.dtypes.value_counts())

In [87]:
dataset_overview(sales_df, "Sales Dataset")
dataset_overview(calendar_df, "Calendar Dataset")
dataset_overview(prices_df, "Selling Prices Dataset")

================================================================================
SALES DATASET
================================================================================
Rows    : 30,490
Columns : 1,919
Memory  : 448.23 MB

Data Types

int64    1913
str         6
Name: count, dtype: int64

================================================================================
CALENDAR DATASET
================================================================================
Rows    : 1,969
Columns : 14
Memory  : 0.26 MB

Data Types

str      7
int64    7
Name: count, dtype: int64

================================================================================
SELLING PRICES DATASET
================================================================================
Rows    : 6,841,121
Columns : 4
Memory  : 318.15 MB

Data Types

str        2
int64      1
float64    1
Name: count, dtype: int64

In [88]:
# ============================================================
# Missing Values Analysis
# ============================================================

def missing_values_report(df, dataset_name):
    
    report = pd.DataFrame({
        "Missing Values": df.isna().sum()
    })

    report["Percentage"] = (
        report["Missing Values"] / len(df)
    ) * 100

    report = report[report["Missing Values"] > 0]

    print("\n" + "=" * 80)
    print(dataset_name)
    print("=" * 80)

    if report.empty:
        print("✅ No missing values found.")
    else:
        display(report.sort_values(
            "Missing Values",
            ascending=False
        ))

In [89]:
missing_values_report(sales_df, "Sales Dataset")

missing_values_report(calendar_df, "Calendar Dataset")

missing_values_report(prices_df, "Selling Prices Dataset")

================================================================================
Sales Dataset
================================================================================
✅ No missing values found.

================================================================================
Calendar Dataset
================================================================================

              Missing Values  Percentage
event_type_2            1964       99.75
event_name_2            1964       99.75
event_type_1            1807       91.77
event_name_1            1807       91.77

================================================================================
Selling Prices Dataset
================================================================================
✅ No missing values found.

In [90]:
# ============================================================
# Duplicate Records
# ============================================================

def duplicate_report(df, name):
    duplicates = df.duplicated().sum()

    print(f"{name:<25} : {duplicates:,}")

In [91]:
duplicate_report(sales_df, "Sales Dataset")
duplicate_report(calendar_df, "Calendar Dataset")
duplicate_report(prices_df, "Selling Prices Dataset")

Sales Dataset             : 0
Calendar Dataset          : 0
Selling Prices Dataset    : 0

In [92]:
display(sales_df.head())

display(calendar_df.head())

display(prices_df.head())

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,d_5,d_6,d_7,d_8,d_9,d_10,d_11,d_12,d_13,d_14,d_15,d_16,d_17,d_18,d_19,d_20,d_21,d_22,d_23,d_24,d_25,d_26,d_27,d_28,d_29,d_30,d_31,d_32,d_33,d_34,d_35,d_36,d_37,d_38,d_39,d_40,d_41,d_42,d_43,d_44,d_45,d_46,d_47,d_48,d_49,d_50,d_51,d_52,d_53,d_54,d_55,d_56,d_57,d_58,d_59,d_60,d_61,d_62,d_63,d_64,d_65,d_66,d_67,d_68,d_69,d_70,d_71,d_72,d_73,d_74,d_75,d_76,d_77,d_78,d_79,d_80,d_81,d_82,d_83,d_84,d_85,d_86,d_87,d_88,d_89,d_90,d_91,d_92,d_93,d_94,d_95,d_96,d_97,d_98,d_99,d_100,d_101,d_102,d_103,d_104,d_105,d_106,d_107,d_108,d_109,d_110,d_111,d_112,d_113,d_114,d_115,d_116,d_117,d_118,d_119,d_120,d_121,d_122,d_123,d_124,d_125,d_126,d_127,d_128,d_129,d_130,d_131,d_132,d_133,d_134,d_135,d_136,d_137,d_138,d_139,d_140,d_141,d_142,d_143,d_144,d_145,d_146,d_147,d_148,d_149,d_150,d_151,d_152,d_153,d_154,d_155,d_156,d_157,d_158,d_159,d_160,d_161,d_162,d_163,d_164,d_165,d_166,d_167,d_168,d_169,d_170,d_171,d_172,d_173,d_174,d_175,d_176,d_177,d_178,d_179,d_180,d_181,d_182,d_183,d_184,d_185,d_186,d_187,d_188,d_189,d_190,d_191,d_192,d_193,d_194,d_195,d_196,d_197,d_198,d_199,d_200,d_201,d_202,d_203,d_204,d_205,d_206,d_207,d_208,d_209,d_210,d_211,d_212,d_213,d_214,d_215,d_216,d_217,d_218,d_219,d_220,d_221,d_222,d_223,d_224,d_225,d_226,d_227,d_228,d_229,d_230,d_231,d_232,d_233,d_234,d_235,d_236,d_237,d_238,d_239,d_240,d_241,d_242,d_243,d_244,d_245,d_246,d_247,d_248,d_249,d_250,d_251,d_252,d_253,d_254,d_255,d_256,d_257,d_258,d_259,d_260,d_261,d_262,d_263,d_264,d_265,d_266,d_267,d_268,d_269,d_270,d_271,d_272,d_273,d_274,d_275,d_276,d_277,d_278,d_279,d_280,d_281,d_282,d_283,d_284,d_285,d_286,d_287,d_288,d_289,d_290,d_291,d_292,d_293,d_294,d_295,d_296,d_297,d_298,d_299,d_300,d_301,d_302,d_303,d_304,d_305,d_306,d_307,d_308,d_309,d_310,d_311,d_312,d_313,d_314,d_315,d_316,d_317,d_318,d_319,d_320,d_321,d_322,d_323,d_324,d_325,d_326,d_327,d_328,d_329,d_330,d_331,d_332,d_333,d_334,d_335,d_336,d_337,d_338,d_339,d_340,d_341,d_342,d_343,d_344,d_345,d_346,d_347,d_348,d_349,d_350,d_351,d_352,d_353,d_354,d_355,d_356,d_357,d_358,d_359,d_360,d_361,d_362,d_363,d_364,d_365,d_366,d_367,d_368,d_369,d_370,d_371,d_372,d_373,d_374,d_375,d_376,d_377,d_378,d_379,d_380,d_381,d_382,d_383,d_384,d_385,d_386,d_387,d_388,d_389,d_390,d_391,d_392,d_393,d_394,d_395,d_396,d_397,d_398,d_399,d_400,d_401,d_402,d_403,d_404,d_405,d_406,d_407,d_408,d_409,d_410,d_411,d_412,d_413,d_414,d_415,d_416,d_417,d_418,d_419,d_420,d_421,d_422,d_423,d_424,d_425,d_426,d_427,d_428,d_429,d_430,d_431,d_432,d_433,d_434,d_435,d_436,d_437,d_438,d_439,d_440,d_441,d_442,d_443,d_444,d_445,d_446,d_447,d_448,d_449,d_450,d_451,d_452,d_453,d_454,d_455,d_456,d_457,d_458,d_459,d_460,d_461,d_462,d_463,d_464,d_465,d_466,d_467,d_468,d_469,d_470,d_471,d_472,d_473,d_474,d_475,d_476,d_477,d_478,d_479,d_480,d_481,d_482,d_483,d_484,d_485,d_486,d_487,d_488,d_489,d_490,d_491,d_492,d_493,d_494,d_495,d_496,d_497,d_498,d_499,d_500,d_501,d_502,d_503,d_504,d_505,d_506,d_507,d_508,d_509,d_510,d_511,d_512,d_513,d_514,d_515,d_516,d_517,d_518,d_519,d_520,d_521,d_522,d_523,d_524,d_525,d_526,d_527,d_528,d_529,d_530,d_531,d_532,d_533,d_534,d_535,d_536,d_537,d_538,d_539,d_540,d_541,d_542,d_543,d_544,d_545,d_546,d_547,d_548,d_549,d_550,d_551,d_552,d_553,d_554,d_555,d_556,d_557,d_558,d_559,d_560,d_561,d_562,d_563,d_564,d_565,d_566,d_567,d_568,d_569,d_570,d_571,d_572,d_573,d_574,d_575,d_576,d_577,d_578,d_579,d_580,d_581,d_582,d_583,d_584,d_585,d_586,d_587,d_588,d_589,d_590,d_591,d_592,d_593,d_594,d_595,d_596,d_597,d_598,d_599,d_600,d_601,d_602,d_603,d_604,d_605,d_606,d_607,d_608,d_609,d_610,d_611,d_612,d_613,d_614,d_615,d_616,d_617,d_618,d_619,d_620,d_621,d_622,d_623,d_624,d_625,d_626,d_627,d_628,d_629,d_630,d_631,d_632,d_633,d_634,d_635,d_636,d_637,d_638,d_639,d_640,d_641,d_642,d_643,d_644,d_645,d_646,d_647,d_648,d_649,d_650,d_651,d_652,d_653,d_654,d_655,d_656,d_657,d_658,d_659,d_660,d_661,d_662,d_663,d_664,d_665,d_666,d_667,d_668,d_669,d_670,d_671,d_672,d_673,d_674,d_675,d_676,d_677,d_678,d_679,d_680,d_681,d_682,d_683,d_684,d_685,d_686,d_687,d_688,d_689,d_690,d_691,d_692,d_693,d_694,d_695,d_696,d_697,d_698,d_699,d_700,d_701,d_702,d_703,d_704,d_705,d_706,d_707,d_708,d_709,d_710,d_711,d_712,d_713,d_714,d_715,d_716,d_717,d_718,d_719,d_720,d_721,d_722,d_723,d_724,d_725,d_726,d_727,d_728,d_729,d_730,d_731,d_732,d_733,d_734,d_735,d_736,d_737,d_738,d_739,d_740,d_741,d_742,d_743,d_744,d_745,d_746,d_747,d_748,d_749,d_750,d_751,d_752,d_753,d_754,d_755,d_756,d_757,d_758,d_759,d_760,d_761,d_762,d_763,d_764,d_765,d_766,d_767,d_768,d_769,d_770,d_771,d_772,d_773,d_774,d_775,d_776,d_777,d_778,d_779,d_780,d_781,d_782,d_783,d_784,d_785,d_786,d_787,d_788,d_789,d_790,d_791,d_792,d_793,d_794,d_795,d_796,d_797,d_798,d_799,d_800,d_801,d_802,d_803,d_804,d_805,d_806,d_807,d_808,d_809,d_810,d_811,d_812,d_813,d_814,d_815,d_816,d_817,d_818,d_819,d_820,d_821,d_822,d_823,d_824,d_825,d_826,d_827,d_828,d_829,d_830,d_831,d_832,d_833,d_834,d_835,d_836,d_837,d_838,d_839,d_840,d_841,d_842,d_843,d_844,d_845,d_846,d_847,d_848,d_849,d_850,d_851,d_852,d_853,d_854,d_855,d_856,d_857,d_858,d_859,d_860,d_861,d_862,d_863,d_864,d_865,d_866,d_867,d_868,d_869,d_870,d_871,d_872,d_873,d_874,d_875,d_876,d_877,d_878,d_879,d_880,d_881,d_882,d_883,d_884,d_885,d_886,d_887,d_888,d_889,d_890,d_891,d_892,d_893,d_894,d_895,d_896,d_897,d_898,d_899,d_900,d_901,d_902,d_903,d_904,d_905,d_906,d_907,d_908,d_909,d_910,d_911,d_912,d_913,d_914,d_915,d_916,d_917,d_918,d_919,d_920,d_921,d_922,d_923,d_924,d_925,d_926,d_927,d_928,d_929,d_930,d_931,d_932,d_933,d_934,d_935,d_936,d_937,d_938,d_939,d_940,d_941,d_942,d_943,d_944,d_945,d_946,d_947,d_948,d_949,d_950,d_951,d_952,d_953,d_954,d_955,d_956,d_957,d_958,d_959,d_960,d_961,d_962,d_963,d_964,d_965,d_966,d_967,d_968,d_969,d_970,d_971,d_972,d_973,d_974,d_975,d_976,d_977,d_978,d_979,d_980,d_981,d_982,d_983,d_984,d_985,d_986,d_987,d_988,d_989,d_990,d_991,d_992,d_993,d_994,d_995,d_996,d_997,d_998,d_999,d_1000,d_1001,d_1002,d_1003,d_1004,d_1005,d_1006,d_1007,d_1008,d_1009,d_1010,d_1011,d_1012,d_1013,d_1014,d_1015,d_1016,d_1017,d_1018,d_1019,d_1020,d_1021,d_1022,d_1023,d_1024,d_1025,d_1026,d_1027,d_1028,d_1029,d_1030,d_1031,d_1032,d_1033,d_1034,d_1035,d_1036,d_1037,d_1038,d_1039,d_1040,d_1041,d_1042,d_1043,d_1044,d_1045,d_1046,d_1047,d_1048,d_1049,d_1050,d_1051,d_1052,d_1053,d_1054,d_1055,d_1056,d_1057,d_1058,d_1059,d_1060,d_1061,d_1062,d_1063,d_1064,d_1065,d_1066,d_1067,d_1068,d_1069,d_1070,d_1071,d_1072,d_1073,d_1074,d_1075,d_1076,d_1077,d_1078,d_1079,d_1080,d_1081,d_1082,d_1083,d_1084,d_1085,d_1086,d_1087,d_1088,d_1089,d_1090,d_1091,d_1092,d_1093,d_1094,d_1095,d_1096,d_1097,d_1098,d_1099,d_1100,d_1101,d_1102,d_1103,d_1104,d_1105,d_1106,d_1107,d_1108,d_1109,d_1110,d_1111,d_1112,d_1113,d_1114,d_1115,d_1116,d_1117,d_1118,d_1119,d_1120,d_1121,d_1122,d_1123,d_1124,d_1125,d_1126,d_1127,d_1128,d_1129,d_1130,d_1131,d_1132,d_1133,d_1134,d_1135,d_1136,d_1137,d_1138,d_1139,d_1140,d_1141,d_1142,d_1143,d_1144,d_1145,d_1146,d_1147,d_1148,d_1149,d_1150,d_1151,d_1152,d_1153,d_1154,d_1155,d_1156,d_1157,d_1158,d_1159,d_1160,d_1161,d_1162,d_1163,d_1164,d_1165,d_1166,d_1167,d_1168,d_1169,d_1170,d_1171,d_1172,d_1173,d_1174,d_1175,d_1176,d_1177,d_1178,d_1179,d_1180,d_1181,d_1182,d_1183,d_1184,d_1185,d_1186,d_1187,d_1188,d_1189,d_1190,d_1191,d_1192,d_1193,d_1194,d_1195,d_1196,d_1197,d_1198,d_1199,d_1200,d_1201,d_1202,d_1203,d_1204,d_1205,d_1206,d_1207,d_1208,d_1209,d_1210,d_1211,d_1212,d_1213,d_1214,d_1215,d_1216,d_1217,d_1218,d_1219,d_1220,d_1221,d_1222,d_1223,d_1224,d_1225,d_1226,d_1227,d_1228,d_1229,d_1230,d_1231,d_1232,d_1233,d_1234,d_1235,d_1236,d_1237,d_1238,d_1239,d_1240,d_1241,d_1242,d_1243,d_1244,d_1245,d_1246,d_1247,d_1248,d_1249,d_1250,d_1251,d_1252,d_1253,d_1254,d_1255,d_1256,d_1257,d_1258,d_1259,d_1260,d_1261,d_1262,d_1263,d_1264,d_1265,d_1266,d_1267,d_1268,d_1269,d_1270,d_1271,d_1272,d_1273,d_1274,d_1275,d_1276,d_1277,d_1278,d_1279,d_1280,d_1281,d_1282,d_1283,d_1284,d_1285,d_1286,d_1287,d_1288,d_1289,d_1290,d_1291,d_1292,d_1293,d_1294,d_1295,d_1296,d_1297,d_1298,d_1299,d_1300,d_1301,d_1302,d_1303,d_1304,d_1305,d_1306,d_1307,d_1308,d_1309,d_1310,d_1311,d_1312,d_1313,d_1314,d_1315,d_1316,d_1317,d_1318,d_1319,d_1320,d_1321,d_1322,d_1323,d_1324,d_1325,d_1326,d_1327,d_1328,d_1329,d_1330,d_1331,d_1332,d_1333,d_1334,d_1335,d_1336,d_1337,d_1338,d_1339,d_1340,d_1341,d_1342,d_1343,d_1344,d_1345,d_1346,d_1347,d_1348,d_1349,d_1350,d_1351,d_1352,d_1353,d_1354,d_1355,d_1356,d_1357,d_1358,d_1359,d_1360,d_1361,d_1362,d_1363,d_1364,d_1365,d_1366,d_1367,d_1368,d_1369,d_1370,d_1371,d_1372,d_1373,d_1374,d_1375,d_1376,d_1377,d_1378,d_1379,d_1380,d_1381,d_1382,d_1383,d_1384,d_1385,d_1386,d_1387,d_1388,d_1389,d_1390,d_1391,d_1392,d_1393,d_1394,d_1395,d_1396,d_1397,d_1398,d_1399,d_1400,d_1401,d_1402,d_1403,d_1404,d_1405,d_1406,d_1407,d_1408,d_1409,d_1410,d_1411,d_1412,d_1413,d_1414,d_1415,d_1416,d_1417,d_1418,d_1419,d_1420,d_1421,d_1422,d_1423,d_1424,d_1425,d_1426,d_1427,d_1428,d_1429,d_1430,d_1431,d_1432,d_1433,d_1434,d_1435,d_1436,d_1437,d_1438,d_1439,d_1440,d_1441,d_1442,d_1443,d_1444,d_1445,d_1446,d_1447,d_1448,d_1449,d_1450,d_1451,d_1452,d_1453,d_1454,d_1455,d_1456,d_1457,d_1458,d_1459,d_1460,d_1461,d_1462,d_1463,d_1464,d_1465,d_1466,d_1467,d_1468,d_1469,d_1470,d_1471,d_1472,d_1473,d_1474,d_1475,d_1476,d_1477,d_1478,d_1479,d_1480,d_1481,d_1482,d_1483,d_1484,d_1485,d_1486,d_1487,d_1488,d_1489,d_1490,d_1491,d_1492,d_1493,d_1494,d_1495,d_1496,d_1497,d_1498,d_1499,d_1500,d_1501,d_1502,d_1503,d_1504,d_1505,d_1506,d_1507,d_1508,d_1509,d_1510,d_1511,d_1512,d_1513,d_1514,d_1515,d_1516,d_1517,d_1518,d_1519,d_1520,d_1521,d_1522,d_1523,d_1524,d_1525,d_1526,d_1527,d_1528,d_1529,d_1530,d_1531,d_1532,d_1533,d_1534,d_1535,d_1536,d_1537,d_1538,d_1539,d_1540,d_1541,d_1542,d_1543,d_1544,d_1545,d_1546,d_1547,d_1548,d_1549,d_1550,d_1551,d_1552,d_1553,d_1554,d_1555,d_1556,d_1557,d_1558,d_1559,d_1560,d_1561,d_1562,d_1563,d_1564,d_1565,d_1566,d_1567,d_1568,d_1569,d_1570,d_1571,d_1572,d_1573,d_1574,d_1575,d_1576,d_1577,d_1578,d_1579,d_1580,d_1581,d_1582,d_1583,d_1584,d_1585,d_1586,d_1587,d_1588,d_1589,d_1590,d_1591,d_1592,d_1593,d_1594,d_1595,d_1596,d_1597,d_1598,d_1599,d_1600,d_1601,d_1602,d_1603,d_1604,d_1605,d_1606,d_1607,d_1608,d_1609,d_1610,d_1611,d_1612,d_1613,d_1614,d_1615,d_1616,d_1617,d_1618,d_1619,d_1620,d_1621,d_1622,d_1623,d_1624,d_1625,d_1626,d_1627,d_1628,d_1629,d_1630,d_1631,d_1632,d_1633,d_1634,d_1635,d_1636,d_1637,d_1638,d_1639,d_1640,d_1641,d_1642,d_1643,d_1644,d_1645,d_1646,d_1647,d_1648,d_1649,d_1650,d_1651,d_1652,d_1653,d_1654,d_1655,d_1656,d_1657,d_1658,d_1659,d_1660,d_1661,d_1662,d_1663,d_1664,d_1665,d_1666,d_1667,d_1668,d_1669,d_1670,d_1671,d_1672,d_1673,d_1674,d_1675,d_1676,d_1677,d_1678,d_1679,d_1680,d_1681,d_1682,d_1683,d_1684,d_1685,d_1686,d_1687,d_1688,d_1689,d_1690,d_1691,d_1692,d_1693,d_1694,d_1695,d_1696,d_1697,d_1698,d_1699,d_1700,d_1701,d_1702,d_1703,d_1704,d_1705,d_1706,d_1707,d_1708,d_1709,d_1710,d_1711,d_1712,d_1713,d_1714,d_1715,d_1716,d_1717,d_1718,d_1719,d_1720,d_1721,d_1722,d_1723,d_1724,d_1725,d_1726,d_1727,d_1728,d_1729,d_1730,d_1731,d_1732,d_1733,d_1734,d_1735,d_1736,d_1737,d_1738,d_1739,d_1740,d_1741,d_1742,d_1743,d_1744,d_1745,d_1746,d_1747,d_1748,d_1749,d_1750,d_1751,d_1752,d_1753,d_1754,d_1755,d_1756,d_1757,d_1758,d_1759,d_1760,d_1761,d_1762,d_1763,d_1764,d_1765,d_1766,d_1767,d_1768,d_1769,d_1770,d_1771,d_1772,d_1773,d_1774,d_1775,d_1776,d_1777,d_1778,d_1779,d_1780,d_1781,d_1782,d_1783,d_1784,d_1785,d_1786,d_1787,d_1788,d_1789,d_1790,d_1791,d_1792,d_1793,d_1794,d_1795,d_1796,d_1797,d_1798,d_1799,d_1800,d_1801,d_1802,d_1803,d_1804,d_1805,d_1806,d_1807,d_1808,d_1809,d_1810,d_1811,d_1812,d_1813,d_1814,d_1815,d_1816,d_1817,d_1818,d_1819,d_1820,d_1821,d_1822,d_1823,d_1824,d_1825,d_1826,d_1827,d_1828,d_1829,d_1830,d_1831,d_1832,d_1833,d_1834,d_1835,d_1836,d_1837,d_1838,d_1839,d_1840,d_1841,d_1842,d_1843,d_1844,d_1845,d_1846,d_1847,d_1848,d_1849,d_1850,d_1851,d_1852,d_1853,d_1854,d_1855,d_1856,d_1857,d_1858,d_1859,d_1860,d_1861,d_1862,d_1863,d_1864,d_1865,d_1866,d_1867,d_1868,d_1869,d_1870,d_1871,d_1872,d_1873,d_1874,d_1875,d_1876,d_1877,d_1878,d_1879,d_1880,d_1881,d_1882,d_1883,d_1884,d_1885,d_1886,d_1887,d_1888,d_1889,d_1890,d_1891,d_1892,d_1893,d_1894,d_1895,d_1896,d_1897,d_1898,d_1899,d_1900,d_1901,d_1902,d_1903,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,1,1,0,0,0,0,0,1,2,1,0,1,1,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,2,1,0,0,0,2,0,0,0,0,0,1,0,0,0,1,0,1,2,1,1,0,0,0,0,1,0,0,1,2,0,1,0,0,1,0,1,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,2,2,0,1,1,0,0,0,1,1,0,1,1,1,1,0,2,3,1,1,0,0,0,0,0,1,0,0,0,0,2,1,0,0,1,1,2,1,1,0,1,0,1,1,0,1,1,0,3,0,0,3,0,1,1,2,0,1,1,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,2,0,0,1,0,2,0,0,0,0,0,0,1,0,1,0,1,1,0,0,0,0,0,1,0,0,0,0,0,1,2,0,0,0,0,0,0,1,2,0,0,0,2,1,2,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,1,1,0,2,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,0,0,1,1,2,0,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,2,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0,1,0,1,0,0,1,0,0,1,1,2,0,1,0,0,0,0,0,0,0,0,3,1,2,2,1,1,0,0,2,0,0,0,0,1,0,1,0,0,0,1,1,0,3,1,0,0,0,0,0,1,0,1,1,1,0,0,0,0,2,0,0,2,0,0,0,1,0,0,0,0,0,4,0,0,2,1,0,0,0,0,0,1,0,0,0,0,0,4,0,1,0,1,2,2,0,0,0,0,2,1,1,1,1,1,0,0,1,0,0,1,0,0,0,1,1,0,1,2,0,0,2,0,1,3,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,1,1,0,1,1,0,0,1,1,1,0,0,0,0,0,2,0,0,0,0,3,0,2,0,0,0,0,3,2,0,2,0,0,2,0,0,0,0,3,0,1,1,1,0,1,0,1,0,0,2,4,0,0,0,0,0,2,0,0,1,0,0,1,1,5,1,1,0,0,0,0,0,0,0,0,2,1,1,0,2,0,2,1,0,1,0,1,1,0,0,0,2,1,1,0,0,1,0,3,0,0,0,1,0,0,2,1,0,1,0,0,3,3,0,0,0,0,0,0,0,1,1,1,0,2,2,2,0,0,1,0,0,1,3,0,0,0,1,1,0,1,0,1,0,0,1,1,1,2,1,1,1,0,2,2,2,1,0,0,0,1,2,0,0,1,2,1,1,1,0,1,0,1,0,0,1,0,1,0,2,1,0,2,0,1,0,0,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,3,1,1,0,1,1,0,0,0,1,1,2,0,0,0,1,0,2,1,0,1,1,0,0,0,1,1,1,3,1,1,0,0,2,0,1,0,0,0,2,0,0,0,4,2,1,0,0,0,0,2,1,0,1,1,0,0,0,1,2,1,1,0,0,2,0,2,2,0,0,0,1,1,0,2,0,1,1,2,0,1,0,0,0,2,1,0,1,1,2,0,0,0,0,0,0,0,1,0,1,0,1,0,3,1,1,0,1,1,2,0,0,0,0,1,1,0,0,0,0,3,0,1,0,0,0,0,1,1,1,0,1,0,2,0,0,0,0,2,0,0,0,0,1,1,2,0,0,0,0,2,0,0,1,1,1,1,0,0,0,0,0,1,2,2,0,1,0,0,0,0,1,2,1,0,0,0,0,0,1,0,3,0,1,2,1,0,3,0,0,0,1,0,2,2,1,0,0,1,2,0,1,0,1,4,0,0,5,0,0,0,0,0,0,2,1,2,1,0,0,0,1,1,1,0,0,1,1,1,1,1,0,0,0,2,2,0,0,1,4,0,0,0,0,1,1,2,0,4,0,1,0,1,4,2,0,2,0,1,1,0,1,0,0,1,1,3,0,0,0,1,1,1,3,1,3,1,2,2,0,1,1,1,1,0,0,0,0,0,1,0,4,2,3,0,1,2,0,0,0,1,1,3,0,1,1,1,3,0,1,1

         date  wm_yr_wk    weekday  wday  month  year    d event_name_1 event_type_1 event_name_2 event_type_2  snap_CA  snap_TX  snap_WI
0  2011-01-29     11101   Saturday     1      1  2011  d_1          NaN          NaN          NaN          NaN        0        0        0
1  2011-01-30     11101     Sunday     2      1  2011  d_2          NaN          NaN          NaN          NaN        0        0        0
2  2011-01-31     11101     Monday     3      1  2011  d_3          NaN          NaN          NaN          NaN        0        0        0
3  2011-02-01     11101    Tuesday     4      2  2011  d_4          NaN          NaN          NaN          NaN        1        1        0
4  2011-02-02     11101  Wednesday     5      2  2011  d_5          NaN          NaN          NaN          NaN        1        0        1

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

# 📊 Business Understanding

### Sales Dataset

Contains historical daily sales for each product across stores.

**Key Fields**

- item_id
- dept_id
- cat_id
- store_id
- state_id
- Daily sales (d_1 ... d_1913)

---

### Calendar Dataset

Contains calendar information including:

- Date
- Week
- Month
- Year
- Holidays
- SNAP eligibility

---

### Selling Prices Dataset

Contains weekly selling prices for each product in each store.

These prices will later be merged with sales data to estimate revenue and build price-related forecasting features.

# 🧼 Data Cleaning & Validation

Raw datasets often contain inconsistencies that can affect downstream analytics and machine learning models.

In this section, we will:

- Check for duplicate records.
- Validate missing values.
- Verify data types.
- Standardize column formats where necessary.
- Ensure the datasets are ready for integration.

All cleaning operations are performed programmatically to ensure the pipeline is reproducible.

In [93]:
# ============================================================
# Create Working Copies
# ============================================================

sales_clean = sales_df.copy()
calendar_clean = calendar_df.copy()
prices_clean = prices_df.copy()

print("✅ Working copies created successfully.")

✅ Working copies created successfully.

In [94]:
# ============================================================
# Duplicate Validation
# ============================================================

datasets = {
    "Sales": sales_clean,
    "Calendar": calendar_clean,
    "Prices": prices_clean
}

for name, df in datasets.items():

    duplicates = df.duplicated().sum()

    print(f"{name:<12} : {duplicates:,} duplicate rows")

Sales        : 0 duplicate rows
Calendar     : 0 duplicate rows
Prices       : 0 duplicate rows

In [95]:
# ============================================================
# Remove Duplicate Records
# ============================================================

sales_clean.drop_duplicates(inplace=True)
calendar_clean.drop_duplicates(inplace=True)
prices_clean.drop_duplicates(inplace=True)

print("✅ Duplicate removal completed.")

✅ Duplicate removal completed.

In [96]:
# ============================================================
# Missing Values Summary
# ============================================================

def summarize_missing(df, name):

    missing = df.isna().sum().sum()

    print(f"{name:<12}: {missing:,} missing values")


summarize_missing(sales_clean, "Sales")
summarize_missing(calendar_clean, "Calendar")
summarize_missing(prices_clean, "Prices")

Sales       : 0 missing values
Calendar    : 7,542 missing values
Prices      : 0 missing values

In [97]:
# ============================================================
# Calendar Missing Values
# ============================================================

calendar_clean.isnull().sum().sort_values(ascending=False)

event_type_2    1964
event_name_2    1964
event_name_1    1807
event_type_1    1807
date               0
wm_yr_wk           0
year               0
month              0
wday               0
weekday            0
d                  0
snap_CA            0
snap_TX            0
snap_WI            0
dtype: int64

## Cleaning Decision – Missing Event Information

The Calendar dataset contains missing values in the event-related columns.

These missing values do **not** indicate poor data quality.

Instead, they represent days on which no special event or holiday occurred.

Therefore:

- Missing values are retained.
- No imputation is performed.
- The missing values themselves carry business meaning.

This decision preserves the integrity of the original dataset.

In [98]:
# ============================================================
# Data Type Validation
# ============================================================

for name, df in datasets.items():

    print("\n" + "="*70)
    print(name)
    print("="*70)

    display(df.dtypes.value_counts())

======================================================================
Sales
======================================================================

int64    1913
str         6
Name: count, dtype: int64

======================================================================
Calendar
======================================================================

str      7
int64    7
Name: count, dtype: int64

======================================================================
Prices
======================================================================

str        2
int64      1
float64    1
Name: count, dtype: int64

In [99]:
# ============================================================
# Convert Date Column
# ============================================================

calendar_clean["date"] = pd.to_datetime(
    calendar_clean["date"]
)

print(calendar_clean["date"].dtype)

datetime64[us]

In [100]:
calendar_clean.head()

        date  wm_yr_wk    weekday  wday  month  year    d event_name_1 event_type_1 event_name_2 event_type_2  snap_CA  snap_TX  snap_WI
0 2011-01-29     11101   Saturday     1      1  2011  d_1          NaN          NaN          NaN          NaN        0        0        0
1 2011-01-30     11101     Sunday     2      1  2011  d_2          NaN          NaN          NaN          NaN        0        0        0
2 2011-01-31     11101     Monday     3      1  2011  d_3          NaN          NaN          NaN          NaN        0        0        0
3 2011-02-01     11101    Tuesday     4      2  2011  d_4          NaN          NaN          NaN          NaN        1        1        0
4 2011-02-02     11101  Wednesday     5      2  2011  d_5          NaN          NaN          NaN          NaN        1        0        1

In [101]:
cleaning_summary = pd.DataFrame({

    "Cleaning Step": [

        "Duplicate Removal",

        "Missing Value Assessment",

        "Date Conversion",

        "Data Type Validation"

    ],

    "Status": [

        "Completed",

        "Completed",

        "Completed",

        "Completed"

    ]

})

cleaning_summary

              Cleaning Step     Status
0         Duplicate Removal  Completed
1  Missing Value Assessment  Completed
2           Date Conversion  Completed
3      Data Type Validation  Completed

# ✅ Data Cleaning Summary

The following cleaning activities were completed:

| Issue | Action Taken | Business Rationale |
|-------|--------------|--------------------|
| Duplicate records | Removed (if present) | Prevent duplicate transactions |
| Missing event information | Retained | Represents non-event days |
| Date format | Converted to datetime | Required for time-series analysis |
| Data types | Validated | Ensure consistency across datasets |

The datasets are now clean, validated, and ready for integration.

# 🔄 Data Integration

The sales dataset is currently stored in a wide format, where each day is represented by a separate column.

For analysis and forecasting, the data must be transformed into a long format, where each row represents a single product, store, and day combination.

The transformed sales data will then be merged with:

- Calendar information
- Selling prices

to produce one analysis-ready dataset.

In [102]:
# ============================================================
# Identifier Columns
# ============================================================

id_columns = [
    "id",
    "item_id",
    "dept_id",
    "cat_id",
    "store_id",
    "state_id"
]

day_columns = [
    col for col in sales_clean.columns
    if col.startswith("d_")
]

print(f"Identifier Columns : {len(id_columns)}")
print(f"Day Columns        : {len(day_columns)}")

Identifier Columns : 6
Day Columns        : 1913

In [103]:
# ============================================================
# Convert Wide Format to Long Format
# ============================================================

sales_long = sales_clean.melt(
    id_vars=id_columns,
    value_vars=day_columns,
    var_name="d",
    value_name="units_sold"
)

print("Transformation completed.\n")

print(sales_long.shape)

sales_long.head()

Transformation completed.

(58327370, 8)

                              id        item_id    dept_id   cat_id store_id state_id    d  units_sold
0  HOBBIES_1_001_CA_1_validation  HOBBIES_1_001  HOBBIES_1  HOBBIES     CA_1       CA  d_1           0
1  HOBBIES_1_002_CA_1_validation  HOBBIES_1_002  HOBBIES_1  HOBBIES     CA_1       CA  d_1           0
2  HOBBIES_1_003_CA_1_validation  HOBBIES_1_003  HOBBIES_1  HOBBIES     CA_1       CA  d_1           0
3  HOBBIES_1_004_CA_1_validation  HOBBIES_1_004  HOBBIES_1  HOBBIES     CA_1       CA  d_1           0
4  HOBBIES_1_005_CA_1_validation  HOBBIES_1_005  HOBBIES_1  HOBBIES     CA_1       CA  d_1           0

In [104]:
print("Rows :", f"{sales_long.shape[0]:,}")
print("Columns :", sales_long.shape[1])

Rows : 58,327,370
Columns : 8

In [105]:
sales_long.to_parquet(
    PROCESSED_DATA_DIR / "sales_long.parquet",
    index=False
)

print("sales_long saved successfully.")

sales_long saved successfully.

## 📅 Merge Calendar Data

The sales data uses day identifiers (`d_1`, `d_2`, ...) that are not directly interpretable.

The calendar dataset provides:

- Actual dates
- Week information
- Month
- Year
- SNAP indicators
- Event information

Merging the calendar dataset enriches the sales records with meaningful temporal features.

In [106]:
# ============================================================
# Merge Sales with Calendar (Chunked)
# ============================================================

id_columns = [
    "id",
    "item_id",
    "dept_id",
    "cat_id",
    "store_id",
    "state_id"
]

day_columns = [c for c in sales_clean.columns if c.startswith("d_")]

chunk_dir = PROCESSED_DATA_DIR / "integration_chunks"
chunk_dir.mkdir(exist_ok=True)

for i, start in enumerate(range(0, len(day_columns), 30), start=1):

    days = day_columns[start:start+30]

    print(f"Processing chunk {i}...")

    sales_chunk = sales_clean.melt(
        id_vars=id_columns,
        value_vars=days,
        var_name="d",
        value_name="units_sold"
    )

    sales_chunk = sales_chunk.merge(
        calendar_clean,
        on="d",
        how="left"
    )

    sales_chunk.to_parquet(
        chunk_dir / f"calendar_chunk_{i:03d}.parquet",
        index=False
    )

    del sales_chunk
    gc.collect()

print("Calendar merge completed successfully.")

Processing chunk 1...
Processing chunk 2...
Processing chunk 3...
Processing chunk 4...
Processing chunk 5...
Processing chunk 6...
Processing chunk 7...
Processing chunk 8...
Processing chunk 9...
Processing chunk 10...
Processing chunk 11...
Processing chunk 12...
Processing chunk 13...
Processing chunk 14...
Processing chunk 15...
Processing chunk 16...
Processing chunk 17...
Processing chunk 18...
Processing chunk 19...
Processing chunk 20...
Processing chunk 21...
Processing chunk 22...
Processing chunk 23...
Processing chunk 24...
Processing chunk 25...
Processing chunk 26...
Processing chunk 27...
Processing chunk 28...
Processing chunk 29...
Processing chunk 30...
Processing chunk 31...
Processing chunk 32...
Processing chunk 33...
Processing chunk 34...
Processing chunk 35...
Processing chunk 36...
Processing chunk 37...
Processing chunk 38...
Processing chunk 39...
Processing chunk 40...
Processing chunk 41...
Processing chunk 42...
Processing chunk 43...
Processing chunk 44...
Processing chunk 45...
Processing chunk 46...
Processing chunk 47...
Processing chunk 48...
Processing chunk 49...
Processing chunk 50...
Processing chunk 51...
Processing chunk 52...
Processing chunk 53...
Processing chunk 54...
Processing chunk 55...
Processing chunk 56...
Processing chunk 57...
Processing chunk 58...
Processing chunk 59...
Processing chunk 60...
Processing chunk 61...
Processing chunk 62...
Processing chunk 63...
Processing chunk 64...
Calendar merge completed successfully.

## 💰 Merge Selling Prices

The calendar-enriched sales data is further integrated with the selling prices dataset.

The selling prices dataset provides the selling price of each product for a specific store and week.

The merge is performed using:

- `store_id`
- `item_id`
- `wm_yr_wk`

To maintain memory efficiency, each calendar chunk is processed individually and written back to disk.

In [107]:
# ============================================================
# Reload Sell Prices
# ============================================================

sell_prices_clean = pd.read_csv(
    RAW_DATA_DIR / "sell_prices.csv"
)

# Remove duplicate rows
sell_prices_clean.drop_duplicates(inplace=True)

# Ensure numeric datatype
sell_prices_clean["sell_price"] = pd.to_numeric(
    sell_prices_clean["sell_price"],
    errors="coerce"
)

# Remove missing prices
sell_prices_clean.dropna(subset=["sell_price"], inplace=True)

print(sell_prices_clean.shape)
sell_prices_clean.head()

(6841121, 4)

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

In [108]:
# ============================================================
# Merge Calendar Chunks with Selling Prices
# ============================================================

import gc

final_chunk_dir = PROCESSED_DATA_DIR / "final_chunks"
final_chunk_dir.mkdir(parents=True, exist_ok=True)

calendar_chunks = sorted(chunk_dir.glob("calendar_chunk_*.parquet"))

print(f"Found {len(calendar_chunks)} calendar chunks.\n")

for i, file in enumerate(calendar_chunks, start=1):

    print(f"Processing {file.name}")

    chunk = pd.read_parquet(file)

    chunk = chunk.merge(
        sell_prices_clean,
        on=["store_id", "item_id", "wm_yr_wk"],
        how="left"
    )

    output_file = final_chunk_dir / f"final_chunk_{i:03d}.parquet"

    chunk.to_parquet(
        output_file,
        index=False
    )

    del chunk
    gc.collect()

print("\nSelling price merge completed successfully.")

Found 64 calendar chunks.

Processing calendar_chunk_001.parquet

Processing calendar_chunk_002.parquet
Processing calendar_chunk_003.parquet
Processing calendar_chunk_004.parquet
Processing calendar_chunk_005.parquet
Processing calendar_chunk_006.parquet
Processing calendar_chunk_007.parquet
Processing calendar_chunk_008.parquet
Processing calendar_chunk_009.parquet
Processing calendar_chunk_010.parquet
Processing calendar_chunk_011.parquet
Processing calendar_chunk_012.parquet
Processing calendar_chunk_013.parquet
Processing calendar_chunk_014.parquet
Processing calendar_chunk_015.parquet
Processing calendar_chunk_016.parquet
Processing calendar_chunk_017.parquet
Processing calendar_chunk_018.parquet
Processing calendar_chunk_019.parquet
Processing calendar_chunk_020.parquet
Processing calendar_chunk_021.parquet
Processing calendar_chunk_022.parquet
Processing calendar_chunk_023.parquet
Processing calendar_chunk_024.parquet
Processing calendar_chunk_025.parquet
Processing calendar_chunk_026.parquet
Processing calendar_chunk_027.parquet
Processing calendar_chunk_028.parquet
Processing calendar_chunk_029.parquet
Processing calendar_chunk_030.parquet
Processing calendar_chunk_031.parquet
Processing calendar_chunk_032.parquet
Processing calendar_chunk_033.parquet
Processing calendar_chunk_034.parquet
Processing calendar_chunk_035.parquet
Processing calendar_chunk_036.parquet
Processing calendar_chunk_037.parquet
Processing calendar_chunk_038.parquet
Processing calendar_chunk_039.parquet
Processing calendar_chunk_040.parquet
Processing calendar_chunk_041.parquet
Processing calendar_chunk_042.parquet
Processing calendar_chunk_043.parquet
Processing calendar_chunk_044.parquet
Processing calendar_chunk_045.parquet
Processing calendar_chunk_046.parquet
Processing calendar_chunk_047.parquet
Processing calendar_chunk_048.parquet
Processing calendar_chunk_049.parquet
Processing calendar_chunk_050.parquet
Processing calendar_chunk_051.parquet
Processing calendar_chunk_052.parquet
Processing calendar_chunk_053.parquet
Processing calendar_chunk_054.parquet
Processing calendar_chunk_055.parquet
Processing calendar_chunk_056.parquet
Processing calendar_chunk_057.parquet
Processing calendar_chunk_058.parquet
Processing calendar_chunk_059.parquet
Processing calendar_chunk_060.parquet
Processing calendar_chunk_061.parquet
Processing calendar_chunk_062.parquet
Processing calendar_chunk_063.parquet
Processing calendar_chunk_064.parquet

Selling price merge completed successfully.

In [109]:
len(list(final_chunk_dir.glob("*.parquet")))

64

In [110]:
sample = pd.read_parquet(
    sorted(final_chunk_dir.glob("*.parquet"))[0]
)

print(sample.shape)

sample.head()

(914700, 22)

,id,item_id,dept_id,cat_id,store_id,state_id,d,units_sold,date,wm_yr_wk,weekday,wday,month,year,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0,NaN
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0,NaN
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0,NaN
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0,NaN
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0,NaN

# 📦 Chunked Data Integration

The transformed sales dataset is too large to be merged entirely in memory on standard hardware.

To improve scalability and memory efficiency, the integration process is performed in chunks.

Each chunk is:

1. Merged with the calendar dataset
2. Merged with the selling prices dataset
3. Saved to disk

Finally, all processed chunks are combined into one analysis-ready dataset.

This approach produces the same final output while significantly reducing memory usage and reflects common industry ETL practices.

# ✅ Analysis-Ready Dataset Verification

After integrating the sales, calendar, and selling prices datasets, the resulting dataset was verified to ensure that:

- All expected columns are present
- Row counts remain consistent across processing
- Data types are appropriate
- The integration process completed successfully

The final integrated dataset is now ready for feature engineering and exploratory data analysis.

In [111]:
# ============================================================
# Verify Final Integrated Chunks
# ============================================================

final_chunk_files = sorted(final_chunk_dir.glob("final_chunk_*.parquet"))

print(f"Total Final Chunks : {len(final_chunk_files)}")

Total Final Chunks : 64

In [112]:
# ============================================================
# Inspect Sample Chunk
# ============================================================

sample = pd.read_parquet(final_chunk_files[0])

print(sample.shape)

sample.head()

(914700, 22)

,id,item_id,dept_id,cat_id,store_id,state_id,d,units_sold,date,wm_yr_wk,weekday,wday,month,year,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0,NaN
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0,NaN
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0,NaN
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0,NaN
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,Saturday,1,1,2011,NaN,NaN,NaN,NaN,0,0,0,NaN

In [113]:
# ============================================================
# Missing Values (Sample Chunk)
# ============================================================

sample.isnull().sum().sort_values(ascending=False)

event_type_2    914700
event_name_2    914700
event_type_1    823230
event_name_1    823230
sell_price      551059
id                   0
state_id             0
store_id             0
cat_id               0
dept_id              0
item_id              0
d                    0
date                 0
units_sold           0
year                 0
month                0
wday                 0
weekday              0
wm_yr_wk             0
snap_CA              0
snap_TX              0
snap_WI              0
dtype: int64

In [114]:
# ============================================================
# Data Types
# ============================================================

sample.dtypes

id                         str
item_id                    str
dept_id                    str
cat_id                     str
store_id                   str
state_id                   str
d                          str
units_sold               int64
date            datetime64[us]
wm_yr_wk                 int64
weekday                    str
wday                     int64
month                    int64
year                     int64
event_name_1               str
event_type_1               str
event_name_2               str
event_type_2               str
snap_CA                  int64
snap_TX                  int64
snap_WI                  int64
sell_price             float64
dtype: object

In [115]:
# ============================================================
# Integration Summary
# ============================================================

print("=" * 60)
print("DATA INTEGRATION COMPLETED")
print("=" * 60)

print(f"Calendar Chunks Processed : {len(calendar_chunks)}")
print(f"Final Chunks Created      : {len(final_chunk_files)}")
print(f"Sample Chunk Rows         : {sample.shape[0]:,}")
print(f"Sample Chunk Columns      : {sample.shape[1]}")

print("\nAnalysis-ready dataset successfully generated using a")
print("memory-efficient chunked ETL pipeline.")

============================================================
DATA INTEGRATION COMPLETED
============================================================
Calendar Chunks Processed : 64
Final Chunks Created      : 64
Sample Chunk Rows         : 914,700
Sample Chunk Columns      : 22

Analysis-ready dataset successfully generated using a
memory-efficient chunked ETL pipeline.

# 📌 Data Integration Summary

The four source datasets were successfully integrated into an analysis-ready format using a scalable, chunk-based ETL pipeline.

The integration process included:

- Transformation of sales data from wide to long format
- Integration with calendar information
- Integration with selling prices
- Memory-efficient chunk processing
- Storage of integrated outputs as Parquet files

This approach enables reproducibility, efficient storage, and downstream analytical processing while remaining suitable for systems with limited memory resources.